ResearchHub/researchhub-web

package.json
pages/user/[authorId]/[tabName]/index.js
yarn.lock

Add SafeURL to social links

---

components/Hypothesis/api/postHypothesisStatus.ts
components/Navbar.js
components/PostPageCard.js
config/api.js
pages/user/[authorId]/[tabName]/index.js

- Use new `censor` / `restore` endpoints
https://github.com/ResearchHub/researchhub-backend/pull/965

Updated censor/retore endpoints for posts, hypothesis

---

components/EditorsDashboard/EditorDashboardCard.tsx

[EditorDashboard] Add Editor of Text next to author

---

config/api.js

- Restoring remove comment endpoint that was accidentally deleted

Restoring removed endpoint

---

components/Navbar.js
config/api.js
pages/referral/[referralCode]/index.js
pages/referral/index.js
redux/transaction.js

Referral program only shows for users in the top 1% of RSC (currently at 138 RSC)

Referral program

---

components/EditorsDashboard/EditorDashboardCard.tsx

Editor leader tag

---

components/Author/Tabs/UserTransactions.js
components/HorizontalTabBar.js
components/ResearchCoin/TransactionCard.js
pages/user/[authorId]/[tabName]/index.js
redux/transaction.js

Transactions showing paper / comment if it's available
Depends on this PR: https://github.com/ResearchHub/researchhub-backend/pull/982

Improved transactions

---

components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
components/UnifiedDocFeed/api/unifiedDocFetch.js
components/UnifiedDocFeed/utils/UnifiedDocFeedUtil.tsx
config/api.js
pages/index.js

- See https://github.com/ResearchHub/researchhub-backend/pull/985 for more details.
- Add `hot_v2=true` as a query string to see preview of new results

Hot Score V2

---

components/PostPageCard.js
config/utils/options.js

- Exposing most discussed filter
- Decoupling boost from vote score

Exposing most discussed filter

---

components/Modals/NewPostModal.tsx
components/Modals/NotePublishModal.tsx
components/Navbar.js
components/NewFeature/TabNewFeature.js
components/ResearchhubOptionCard.tsx

**What?**
- When opening the publishing modal, the current user is assigned as the default author.
- Added New badge for ELN features

Default author when publishing and New badge for ELN features

---

components/Modals/AuthorSupportModal.js
components/Modals/PaperTransactionModal.js
components/Modals/WithdrawalModal.js
components/Notifications/Notification.js
components/Notifications/NotificationEntry.js
components/ResearchCoin/TransactionCard.js
config/utils/crypto.js
package.json
pages/user/[authorId]/[tabName]/index.js

Added etherscan TX hash to withdraw flow on FE
FE is also calling a new endpoint for withdrawals

Updated RSC Withdraw Flow

---

components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
components/UnifiedDocFeed/utils/UnifiedDocFeedUtil.tsx

- Initially we had an auto prefetch in case we may want to switch how loading works in the future
- This turned out to be clumsy due to how the UI is currently implemented. 
- Removing this & preloading on button click only
- https://staging-web.researchhub.com/?type=paper

[Feed] Remove Auto Preload

---

components/Activity/ActivityList.js
components/Author/Tabs/FeedCard.tsx
components/Home/SubscribedHubList.js
components/Hubs/FeedList.js
components/Hubs/HubsList.js
components/Leaderboard/LeaderboardContainer.js
components/Paper/SideColumn/ColumnAuthors.js
components/UnifiedDocFeed/utils/getDocumentCard.tsx

**What?**
- switched FeedCard to use `<Link>` instead of `router.push`
- fixed some visual bugs on paper page
- cleaned up borders on homepage sidebar

Switched FeedCard to use <Link> instead of router.push

---

components/Modals/NotePublishModal.tsx
components/Paper/SideColumn/ColumnDOI.js
components/Paper/SideColumn/ColumnDate.js
components/Paper/SideColumn/HubCard.js
components/Paper/SideColumn/PaperSideColumn.js
components/PostPageCard.js
components/ResearchCoin/TransactionCard.js

Added Crossref DOIs to publishing (Frontend)

---

components/GoogleLogin.tsx
components/Navbar.js

Everytime login is clicked, generate the google oauth client

Fix issue with login on mobile

---

components/Author/Tabs/FeedCard.tsx
components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
pages/about/index.js

**What?**
- Added year to feed cards, closes #1140
- Adjusted header css
- Fixed css on about page for mobile
- Added RSC Notion link to about page

Various UI improvements

---

components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx

Fixed server side rendering issue with feed

---

components/Author/Tabs/FeedCard.tsx
components/DiscussionPostMetadata.js
components/Paper/SideColumn/ColumnDOI.js
components/ShareModal.js
components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
components/UnifiedDocFeed/utils/UnifiedDocFeedUtil.tsx

**What?**
- Fixed bug where feed cleared upon clicking logo
- Closes #1148
- Closes #1150
- Fixed feed cards for search
- Updated DOI css on post page

Various bug fixes

---

components/AuthorClaimCaseDashboard/AuthorClaimCaseCard.tsx
components/AuthorClaimCaseDashboard/AuthorClaimCaseContainer.tsx
components/AuthorClaimCaseDashboard/api/AuthorClaimCaseGetCases.ts
config/api.js
config/themes/colors.js

[AuthorClaim] Case Pagination 

---

components/Modals/NoteTemplateModal.tsx
components/Notebook/Notebook.js
components/Notebook/NotebookSidebar.js
config/api.js

Added ability to delete templates

---

components/DiscussionPostMetadata.js
config/api.js

Passing in document type into the flag endpoint

Flagging Discussions Bugfix

---

components/shared/UserApiTokenInputField.tsx
config/api.js
config/utils/copyInputValToClipboard.ts
pages/settings.js

User api token

---

components/ALink.tsx
components/Author/Feed/AuthorFeedItem.js
components/Author/Tabs/FeedCard.tsx
components/Form/DropdownButton.js
components/Form/ScoreInput.tsx
components/Form/Toggle.tsx
components/Hypothesis/HypothesisContainer.tsx
components/Paper/PaperMetadata.js
components/Paper/Tabs/DiscussionTab.js
components/Paper/Tabs/SummaryTab.js
components/PaperPageCard.js
components/PeerReviews/PeerReviewScoreSummary.tsx
components/TextEditor/QuillTextEditor.js
components/TextEditor/index.js
components/Threads/DiscussionEntry.js
components/Threads/PostingGuidelinesModal.tsx
components/Threads/ThreadTextEditor.js
components/UnifiedDocFeed/utils/getDocumentCard.tsx
config/api.js
config/fetch.js
config/types/peerReview.ts
config/utils/id.ts
pages/post/[documentId]/[title]/index.js
redux/discussion/index.js
redux/paper/index.js

Peer Reviews

---

components/Notifications/PaperUploadStateNotifier.tsx
components/Paper/UploadWizard/PaperUploadWizardContainer.tsx
components/Paper/UploadWizard/PaperUploadWizardHeader.tsx
components/Paper/UploadWizard/PaperUploadWizardStandbyBody.tsx
components/Paper/UploadWizard/PaperUploadWizardUpdatePaper.tsx
components/Paper/UploadWizard/api/createAsyncPaperUpdator.ts
components/Paper/UploadWizard/api/createPaperSubmissionWithDOI.ts
components/Paper/UploadWizard/api/createPaperSubmissionWithURL.ts
components/Paper/UploadWizard/types/PaperUploadWizardTypes.ts
config/api.js

Async Paper Updator 

---

components/Form/FormSelect.js
components/Paper/UploadWizard/PaperUploadWizardUpdatePaper.tsx

Updator Hotfix for Ui update & hub selector index

---

components/Flag/FlagButtonV2.tsx
components/Flag/api/postGrmFlag.tsx
components/Hypothesis/HypothesisPageCard.tsx
components/Hypothesis/api/postHypothesisFlag.ts
components/PaperPageCard.js
components/PostPageCard.js
components/Threads/CommentEntry.js
components/Threads/DiscussionEntry.js
components/Threads/ReplyEntry.js
components/Threads/ThreadActionBar.js
config/api.js

Grm flag api

---

components/AuditContent/AuditContentDashboard.tsx
components/AuditContent/FlaggedContentDashboard.tsx
components/Flag/FlagButtonV2.tsx
components/Flag/api/postGrmFlag.tsx
components/Hypothesis/HypothesisPageCard.tsx
components/PaperPageCard.js
components/PostPageCard.js
components/Threads/CommentEntry.js
components/Threads/DiscussionEntry.js
components/Threads/ReplyEntry.js
components/Threads/ThreadActionBar.js
config/api.js

- path resolving for comment types 
- refactor comment handling
- refactor error & success msg handling

[Flagging] - Path resolve & Refactor Msg Handling

---

components/AuditContent/AuditContentDashboard.tsx
components/DiscussionComment.js
components/Hypothesis/Citation/table/CitationConsensusItem.tsx
components/Hypothesis/Citation/table/CitationVoteItem.tsx
components/Moderator/useEffectCheckModCredentials.tsx
components/Navbar.js
components/PermissionsDashboard/PermissionsDashboard.tsx
components/shared/ModeratorDashboardSidebar.tsx
config/gatekeeper/gateKeepCurrentUser.ts
config/gatekeeper/gatekeeper_configs/gatekeeper_configs.ts
config/utils/getCurrentUser.ts
config/utils/nullchecks.ts
config/utils/reputation.js
config/utils/user.js
pages/moderators/audit/all.tsx
pages/moderators/audit/flagged.tsx
pages/moderators/author-claim-case-dashboard/index.tsx
pages/moderators/editors/index.tsx
pages/moderators/permissions/index.tsx
pages/moderators/rsc/index.tsx

- refactor mod cred check. 
- Added getCurrentUser. 
- Updated Permissions for audits

[Flag] - UI Permissions

---

components/AuditContent/FlaggedContentDashboard.tsx
components/AuditContent/utils/renderContributionEntry.tsx
components/Hubs/LiveFeedNotification.js
components/Navbar.js
components/Reputation.js
config/themes/colors.js
pages/user/[authorId]/[tabName]/index.js

Live feed fix, hide RSC balance

---

config/api.js

Audit Dashboard

---

components/AuditContent/AuditContentDashboard.tsx
components/AuditContent/FlaggedContentDashboard.tsx
components/AuditContent/utils/renderContributionEntry.tsx
config/types/contribution.ts

Bug fix: Handling case where author of content does not exist in flagging dash

[Flagging] Handling case where author of content does not exist

---

components/Paper/UploadWizard/PaperUploadWizardDOIBody.tsx
components/Paper/UploadWizard/PaperUploadWizardPDFUpload.tsx
components/Paper/UploadWizard/PaperUploadWizardUrlOrDOIBody.tsx

Opening captcha modal on HTTP 429 in paper upload flow

Throttle Modal in Paper Upload Flow

---

components/Hubs/LiveFeedNotification.js
components/Notifications/Notification.js
components/Notifications/NotificationEntry.js

[ContentModeration] - Flagging & Notification 

---

components/Paper/UploadWizard/PaperUploadWizardPDFUpload.tsx

Capturing all pdf upload errors
Updating generic message

Paper PDF Upload Errors

---

components/Author/Tabs/FeedCard.tsx
components/UnifiedDocFeed/utils/getDocumentCard.tsx

Add Featured UI Card

---

components/Moderator/useEffectCheckModCredentials.tsx
pages/moderators/permissions/index.tsx

updating permissions for permissionsDash

---

components/Modals/NewPostModal.tsx
components/NewPostButton.tsx
components/ResearchHubPopover.tsx
components/ResearchhubOptionCard.tsx
config/killswitch/killswitch_config/killswitch_configs.ts
config/themes/colors.js
config/utils/getIsOnMobileScreenSize.ts
config/utils/useEffectOnScreenResize.ts

- updated & added screen size handlers 
- created popover options for newPostButtons
- update killswitch for bounty questions
- update modal handling logic to reroute 
- Regular screen size
- Mobile screen Size ( kept the modal to take over entire screen)

Dropdown new post buttons

---

components/Hubs/HubPage.js
components/Navbar.js
components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx

https://user-images.githubusercontent.com/17622930/178318378-91b6157d-6a03-4051-bb97-3ce9235423c8.mov

Homepage & Navbar Fixed Width & Banner

---

components/CKEditor/CKEditor.css
components/CKEditor/ELNEditor.js
components/CKEditor/SimpleEditor.js
components/Modals/NoteTemplateModal.tsx
components/Notebook/NotebookSidebar.js
components/Placeholders/DocumentHeaderPlaceholder.js
components/PostPageCard.js
package.json
pages/stylesheets/App.css
yarn.lock

https://www.loom.com/share/639d56cf3c904cc09a740dadb06a99ad
Added video uploads as well as a new way to access the menu via the block button on the left

Upload Videos

---

components/Author/Feed/AuthorFeedItem.js
components/Author/Feed/utils/AuthorFeedUtils.js
components/Author/Tabs/FeedCard.tsx
components/Document/DocumentHeader.tsx
components/Hubs/LiveFeedNotification.js
components/Notifications/Notification.js
components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
components/UnifiedDocFeed/UnifiedDocFeedMenu.js
components/UnifiedDocFeed/api/unifiedDocFetch.js
components/UnifiedDocFeed/utils/UnifiedDocFeedUtil.tsx
components/UnifiedDocFeed/utils/getDocumentCard.tsx
components/Vote/utils/createVoteHandler.ts
config/utils/getUnifiedDocType.ts
config/utils/url_patterns.ts
pages/index.js
pages/my-hubs/index.js

QUESTIONS FOR
- profile page
- Feed

[Question][2/n] integration

---

components/Activity/ActivityCard.js
components/Author/Feed/AuthorFeedItem.js
components/Author/Feed/utils/AuthorFeedUtils.js
components/Author/Tabs/FeedCard.tsx
components/Document/DocumentHeader.tsx
components/Hubs/LiveFeedNotification.js
components/Notifications/Notification.js
components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
components/UnifiedDocFeed/UnifiedDocFeedMenu.js
components/UnifiedDocFeed/api/unifiedDocFetch.js
components/UnifiedDocFeed/utils/UnifiedDocFeedUtil.tsx
components/UnifiedDocFeed/utils/getDocumentCard.tsx
components/Vote/utils/createVoteHandler.ts
config/utils/getUnifiedDocType.ts
config/utils/url_patterns.ts
pages/index.js
pages/my-hubs/index.js

- Reinserting lost question work

Question integration2

---

components/Modals/NotePublishModal.tsx
components/Paper/Upload/api/getSuggestedHubs.ts

Screen sci con hubs starting 07/23/2022 00:00:00 GMT-0700

---

components/Bounty/CreateBountyBtn.tsx
components/Hubs/HubPage.js
components/PostPageCard.js
components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
components/UnifiedDocFeed/UnifiedDocFeedMenu.js
config/killswitch/killswitch_config/killswitch_configs.ts

- Question in homepage filter 
- bounty ks removal 
- remove SciCon Banner 
- remove unused ks configs

[Question] 

---

components/Notifications/NotificationEntry.js
components/Notifications/NotificationHelpers.js

Bounty Notifications

---

components/Notifications/NotificationEntry.js

Anonymizing Editor Flags/Removals of Content

---

components/Document/DocumentActions.tsx
config/types/bounty.ts
config/utils/dates.js

[Bounty] Timestamp ago round up

---

components/Author/Tabs/FeedCard.tsx
components/DocumentBadge.js
components/Flag/api/postGrmFlag.tsx
components/Modals/NotePublishModal.tsx
components/Notifications/Notification.js
components/PostPageCard.js
components/Question/api/createQuestion.ts
components/UnifiedDocFeed/api/unifiedDocFetch.js
components/UnifiedDocFeed/utils/getDocumentCard.tsx
components/Vote/utils/createVoteHandler.ts
config/api.js
config/types/root_types.ts
config/utils/getUnifiedDocType.ts
pages/post/[documentId]/[title]/index.js
pages/post/[documentId]/index.js
tests/cypress/fixtures/unified-feed.json
tests/cypress/integration/ui/home.spec.js

- Rh posts doctype resolve
- depends on https://github.com/ResearchHub/researchhub-backend/pull/1131
- able to load pages
- able to create / load comment modules
- able to query document types from feed.

Rh posts doctype resolve

---

components/Paper/Tabs/PaperTab.js

Updating logic for showing PDF upload

PDF Open Access Upload 

---

components/UnifiedDocFeed/UnifiedDocFeedMenu.js
config/utils/getUnifiedDocType.ts

Renaming questions -> question

Question Filter Bugfix

---

components/Bounty/BountyModal.tsx
config/types/bounty.ts
config/utils/analytics.ts
pages/post/[documentId]/[title]/index.js

Tracking creating and awarding bounties

Bounty Tracking

---

components/Author/Tabs/FeedCard.tsx
components/Bounty/api/fetchBountiesAPI.ts
components/CKEditor/CKEditor.css
components/CKEditor/SimpleEditor.js
components/Document/SubmissionDetails.tsx
components/Paper/Tabs/stylesheets/custom-editor.css
components/Question/AskQuestionForm.tsx
components/UnifiedDocFeed/FeedBlurWithButton.tsx
components/UnifiedDocFeed/FeedInfoCard.tsx
components/UnifiedDocFeed/FeedOrderingDropdown.tsx
components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
components/UnifiedDocFeed/UnifiedDocFeedMenu.js
components/UnifiedDocFeed/UnifiedDocFeedUtil.ts
components/UnifiedDocFeed/api/unifiedDocFetch.js
components/UnifiedDocFeed/constants/UnifiedDocFilters.ts
components/UnifiedDocFeed/utils/UnifiedDocFeedUtil.tsx
components/UnifiedDocFeed/utils/getDocumentCard.tsx
components/UnifiedDocFeed/utils/getEditorUserIDsFromHubs.tsx
config/api.js
config/themes/colors.js
config/types/bounty.ts
config/types/contentType.ts
config/utils/dates.js
config/utils/getUnifiedDocType.ts
package.json
pages/hubs/[slug]/index.js
pages/index.js
pages/my-hubs/index.js
pages/stylesheets/App.css
yarn.lock

New PR for net changes only
https://github.com/ResearchHub/researchhub-web/pull/1236

Bounties in Feed, Types as filters

---

components/Home/sidebar/HomeSidebarBountiesSection.tsx
components/Home/sidebar/sidebar_items/BountiesSidebarItem.tsx

- reflecting comments in https://github.com/ResearchHub/researchhub-web/pull/1243

[HomeRevamp][RightSidebar][4/4] - Requested Code changes in first branch 

---

components/Author/Tabs/FeedCard.tsx
components/Document/SubmissionDetails.tsx
config/types/bounty.ts

- Updated style for cards w/bounties
- No longer rendering title/body of comment if comment bounties exist

Update style for cards with bounties

---

components/Author/Tabs/FeedCard.tsx
components/Bounty/BountyAlert.tsx
components/Bounty/BountyModal.tsx
components/Bounty/CreateBountyBtn.tsx
components/DiscussionPostMetadata.js
components/Document/DocumentHeader.tsx
components/Paper/Tabs/DiscussionTab.js
components/PostPageCard.js
components/Search/Search.js
components/TextEditor/QuillTextEditor.js
components/Threads/CommentEntry.js
components/Threads/DiscussionEntry.js
components/Threads/ThreadActionBar.js
components/Tooltips/NewFeatureTooltip.tsx
config/themes/icons.js
pages/post/[documentId]/[title]/index.js

Allowing users to add to bounties

Group Bounties

---

components/Paper/Tabs/DiscussionTab.js
components/Search/Search.js
components/Threads/CommentEntry.js
components/Threads/ThreadActionBar.js
components/UnifiedDocFeed/FeedMenu/FeedMenu.tsx
components/UnifiedDocFeed/FeedMenu/FeedMenuSortDropdown.tsx
components/UnifiedDocFeed/FeedMenu/FeedMenuTab.tsx
components/UnifiedDocFeed/FeedMenu/FeedMenuTagDropdown.tsx
components/UnifiedDocFeed/UnifiedDocFeedUtil.ts
components/UnifiedDocFeed/api/unifiedDocFetch.js
components/UnifiedDocFeed/constants/UnifiedDocFilters.ts
components/UnifiedDocFeed/constants/UnifiedDocFilters.tsx
components/UnifiedDocFeed/utils/converToBackendFilters.ts
components/UnifiedDocFeed/utils/getSelectedUrlFilters.ts
components/UnifiedDocFeed/utils/handleFilterSelect.ts
config/api.js
config/utils/getUnifiedDocType.ts

Tag filters dropdown, new sort options for bounties

---

components/Modals/ContentSupportModal.js
components/Modals/PaperTransactionModal.js
components/Widget/WidgetContentSupport.js

- Cannot delete a leading "0" in input field
- Added error alert if value less than 0
- Fix issue where tooltip shows on top of input field
- Default to 50 RSC

Various fixes related to the award RSC modal

---

components/Widget/WidgetContentSupport.js

Prevent award tooltip from showing multiple times

hotfix: prevent tooltip from showing multiple times

---

components/UnifiedDocFeed/FeedBlurWithButton.tsx

Change "View All Hubs" button on My Hubs to link to /hubs

---

components/Banner/ExitableBanner.tsx
components/Home/sidebar/HomeRightSidebar.tsx
components/shared/carousel/RhCarousel.tsx
components/shared/carousel/RhCarouselItem.tsx
package.json
yarn.lock

https://www.loom.com/share/592d0b8145364a1385fbb35375feebb1

Adding animation to learning module and also fixing the height

---

components/Bounty/BountyAlert.tsx
components/Document/DocumentHeader.tsx
components/Document/SubmissionDetails.tsx
components/Modals/NewPostModal.tsx
components/PostPageCard.js
components/shared/AuthorFacePile.tsx

Desktop
Bounty user visiting page
Mobile

updated look and feel of bounty alert

---

components/Notifications/Notification.js
components/Notifications/NotificationEntry.js
config/shims.js
pages/settings.js

Removed conditional rendering
Now rendering backend generated content

Notification Refactor

---

components/Banner/ExitableBanner.tsx
components/Banner/constants/exitable_banner_keys.ts
components/Home/sidebar/HomeRightSidebar.tsx
components/Home/sidebar/HomeSidebarBountiesSection.tsx
components/Home/sidebar/HomeSidebarFeaturedDocsSection.tsx
components/Home/sidebar/sidebar_items/BountiesSidebarItem.tsx
components/Home/sidebar/styles/HomeRightSidebarStyles.ts
components/Hubs/HubPage.js
components/shared/AuthorFacePile.tsx
components/shared/carousel/RhCarousel.tsx
components/shared/carousel/RhCarouselItem.tsx

rightsidebar limit hotfix && style updates

---

components/Bounty/BountyAlert.tsx
components/Bounty/BountyModal.tsx
components/Bounty/BountySuccessScreen.tsx
components/Bounty/CreateBountyBtn.tsx
components/Bounty/utils/buildTwitterUrl.ts
components/ShareDropdown.tsx
pages/paper/[paperId]/[paperName]/index.js

- Updated look and feel
- Update twitter message
- Created share to twitter/linked dropdown
- Refactor twitter message 
https://www.loom.com/share/9226fd83dbc04fd1afec53db9753cda1

Bounty Alert Updates

---

components/Admin/AdminButton.tsx
components/TextEditor/QuillTextEditor.js
components/TextEditor/ReviewCategorySelector.tsx
components/TextEditor/stylesheets/QuillTextEditor.css
components/UnifiedDocFeed/utils/converToBackendFilters.ts
config/api.js

- Corresponding BE PR https://github.com/ResearchHub/researchhub-backend/pull/1173
- Now working with Leo's new filtering changes
- Visual fixes to Quill post homepage redesign launch

Bringing back admin button functionality

---

components/Bounty/BountyAlert.tsx
components/Document/SubmissionDetails.tsx
components/Referral/InviteModal.tsx
components/UnifiedDocFeed/FeedMenu/FeedMenuTopLevelFilters.tsx

- Deleted User => Anonymous;
- Dont wrap My Hubs;
- Remove Invitee details in invite modal
- Change benefit lang in invite modal

Various little FE fixes

---

components/Leaderboard/LeaderboardUser.js
pages/leaderboard/LeaderboardPage.js

Showing by default the past month and changing rep title based on timeframe

past month leaderboard

---

components/Home/sidebar/RootLeftSidebar.tsx
components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
config/api.js
next.config.js
pages/_app.js
pages/hubs/[slug]/index.js
pages/hubs/[slug]/live.tsx
pages/index.js
pages/paper/[paperId]/[paperName]/index.js

- Remove `getInitialProps` in HP and hub pages so that pages are cached in CDN
- Turned off user controlled sidebar toggle to prevent layout shift

Vercel Prep

---

components/Author/Tabs/FeedCard.tsx
components/Hypothesis/Citation/modal/AddNewSourceBodySearch.tsx
components/Hypothesis/Citation/search/SourceSearchInput.tsx
components/Hypothesis/Citation/search/SourceSearchInputItem.tsx
components/Hypothesis/Citation/table/CitationConsensusItem.tsx

[Hypothesis] - Citation Comments & Updates Fixes

---

config/types/bounty.ts

Updating default expiration date to 7 days

Bounty Expiration Date

---

components/LiveFeed/Contribution/ContributionHeader.tsx
config/types/contribution.ts

Updated parsing function to correctly parse recipient and created by

RSC Support Live Feed Bugfix

---

components/ALink.tsx
components/Home/sidebar/HomeRightSidebar.tsx
components/Hubs/HubPage.js

and a bug fix that prevent visiting user profile pages

Reputation Hackathon Banner

---

components/Paper/Upload/PaperUploadV2Create.tsx
components/Paper/Upload/api/uploadNewPaper.ts

Updated variable name to use the correct variable for hubs

Direct PDF Upload Hub Bugfix

---

components/Bounty/AwardBountyModal.tsx
components/Bounty/BountyAlert.tsx
config/types/bounty.ts

Bounty being properly set for the multicontribute case

Multi bounty

---

components/Bounty/CreateBountyBtn.tsx
components/Comment/CommentAuthors.tsx
components/Comment/CommentEditor.tsx
components/Comment/CommentEditorToolbar.tsx
components/Comment/CommentFeed.tsx
components/Comment/CommentFilters.tsx
components/Comment/CommentHeader.tsx
components/Comment/CommentSidebar.tsx
components/Comment/CommentSidebarToggle.tsx
components/Comment/CommentSort.tsx
components/Comment/CommentTypeSelector.tsx
components/Comment/hooks/useQuill.tsx
components/Comment/lib/buildQuillModules.ts
components/Comment/lib/colors.ts
components/Comment/lib/commentTypes.tsx
components/Comment/lib/options.tsx
components/Comment/lib/quill.css
components/Icons/IconButton.tsx
components/shared/AuthorFacePile.tsx
pages/_app.js
pages/paper/[paperId]/[paperName]/index.js

- Comment sidebar component
- Styling progress
- Sidebar sliding animation
- Toggle switch for sidebar

Comment system v2, part III

---

components/Comment/CommentFeed.tsx
components/Comment/CommentMenu.tsx
components/Comment/lib/api.ts
components/Comment/lib/contexts.ts
components/Comment/lib/removeComment.ts
components/Comment/lib/replaceComment.ts
pages/paper/[paperId]/[paperName]/index.js
pages/post/[documentId]/[title]/index.js

Giving users the ability to Remove their comments through the UI

Remove comments UI

---

components/ReferenceManager/references/reference_item/ReferenceItemDrawer.tsx
components/ReferenceManager/references/reference_table/utils/formatReferenceRowData.ts
components/ReferenceManager/references/reference_uploader/ReferenceManualUploadDrawer.tsx
components/ReferenceManager/references/utils/resolveFieldKeyLabels.ts

- Updated the “Add Entry” section to be sticky
- DOI input and reference type input order changed
- Update letter casings  on drawer title fixed
- Duplicate DOI input field bug fixed.

[Reference Manager][8/n] - Upload Feedback Update

---

components/Comment/CommentActions.tsx
components/Comment/CommentHeader.tsx
pages/post/[documentId]/[title]/index.js

Addresses the following: 
#1372 
#1374 
#1375

Sidebar off; allow bounty award of any comment; Incorrect profile on hover;

---

components/Comment/lib/api.ts

Using `/censor` endpoint to delete comment

[Comments] Update delete endpoint to /censor

---

components/ReferenceManager/basic_page_layout/BasicPageLayout.tsx
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/form/ReferenceSwitchInput.tsx
components/ReferenceManager/form/ReferenceUserInviteInput.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/api/fetchCurrentUserReferenceCitations.ts
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
components/ReferenceManager/references/reference_organizer/api/fetchReferenceProjects.ts
components/ReferenceManager/references/reference_organizer/api/upsertReferenceProject.ts
components/ReferenceManager/references/reference_organizer/styles/projects_upsert_modal_style.ts
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_uploader/ReferenceManualUploadDrawer.tsx
components/ReferenceManager/references/reference_uploader/reference_upload_utils.ts
config/api.js

- Depends on BE: https://github.com/ResearchHub/researchhub-backend/pull/1250
https://user-images.githubusercontent.com/17622930/234583055-363959f6-78b4-4b58-8da0-853fa05b98f2.mov

[ReferenceManager][Projects][1/n] 

---

components/AuthorAvatar.js
components/AvatarUpload.js
components/Modals/BaseModal.js
components/Org/OrgAvatar.js
components/ReferenceManager/onboarding/ImportReferences.tsx
components/ReferenceManager/onboarding/Organization.tsx
components/ReferenceManager/onboarding/Teammates.tsx
components/ReferenceManager/onboarding/Welcome.tsx
components/ReferenceManager/onboarding/api.tsx
components/ReferenceManager/onboarding/sharedOnboardingStyles.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_uploader/reference_upload_utils.ts
components/UploadFileDragAndDrop.tsx
components/contexts/OrganizationContext.tsx
pages/Base.js
pages/_document.js
pages/reference-manager/[organization].tsx
pages/reference-manager/index.tsx
pages/reference-manager/onboarding/[step].tsx

Onboarding and minor tweaks to upload flow

Onboarding

---

components/Referral/InviteModal.tsx

Fixes https://github.com/ResearchHub/researchhub-web/issues/1392

[Referral] Closes #1392

---

components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/references/ReferencesRoot.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectNavbarElOptions.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
components/ReferenceManager/references/reference_organizer/api/fetchReferenceProjects.ts
components/ReferenceManager/references/reference_organizer/api/upsertReferenceProject.ts
components/ReferenceManager/references/reference_organizer/context/ReferenceProjectsUpsertContext.tsx
components/ReferenceManager/references/reference_organizer/renderNestedReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_uploader/reference_upload_utils.ts
components/contexts/OrganizationContext.tsx

- depends on https://github.com/ResearchHub/researchhub-backend/pull/1269
- permssions get
- create api
- update api
- sub project api
https://user-images.githubusercontent.com/17622930/236843312-0124d6a9-0b23-4f75-859a-eb5c16fc26e7.mov

[ReferenceManager][Projects][3/n] - Projects Upsert Context Migration

---

components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/references/reference_organizer/ReferenceCollaboratorsSection.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
components/ReferenceManager/references/reference_organizer/api/upsertReferenceProject.ts
components/ReferenceManager/references/reference_organizer/renderNestedReferenceProjectsNavbarEl.tsx
config/api.js

https://github.com/ResearchHub/researchhub-web/assets/17622930/b4a47d09-1a4f-4805-a5e1-1eae59e959b2

[RM][Usability][2/n] - User Permissions & Reference Pulling

---

components/ALink.tsx
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarButton.tsx
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/form/ReferenceItemRhUserLookupInput.tsx
components/ReferenceManager/form/ReferenceItemRhUserLookupInputTag.tsx
components/ReferenceManager/form/ReferenceTypeSelect.tsx
components/ReferenceManager/menu/QuickModal.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/ReferencesRoot.tsx
components/ReferenceManager/references/api/fetchCurrentUserReferenceCitations.ts
components/ReferenceManager/references/reference_organizer/ReferenceCollaboratorsSection.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectNavbarElOptions.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
components/ReferenceManager/references/reference_organizer/ReferenceUserInviteSection.tsx
components/ReferenceManager/references/reference_organizer/api/removeReferenceProject.ts
components/ReferenceManager/references/reference_organizer/api/upsertReferenceProject.ts
components/ReferenceManager/references/reference_organizer/context/ReferenceProjectsUpsertContext.tsx
components/ReferenceManager/references/reference_organizer/renderNestedReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/SearchSuggestion/SuggestUsers.tsx
config/api.js

https://github.com/ResearchHub/researchhub-web/assets/17622930/1a62a55a-be62-43d4-a014-016d6fef5acf

[ReferenceManager][Usability][1/n] - Collaboration Custom Lookup UI

---

components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/form/ReferenceItemRhUserLookupInputTag.tsx
components/ReferenceManager/menu/DropdownMenu.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/api/removeReferenceCitations.ts
components/ReferenceManager/references/reference_organizer/ReferenceCollaboratorsSection.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectNavbarElOptions.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
components/ReferenceManager/references/reference_organizer/api/fetchReferenceOrgProjects.ts
components/ReferenceManager/references/reference_organizer/context/ReferenceProjectsUpsertContext.tsx
components/ReferenceManager/references/reference_organizer/renderNestedReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
config/api.js

https://github.com/ResearchHub/researchhub-web/assets/17622930/e0be020b-1359-4696-8a20-508310197555

[RM][Usability] - Delete Refs & Viewer / Editor User Mod

---

components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/ReferencesRoot.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/context/ReferenceActiveProjectContext.tsx
components/ReferenceManager/references/reference_organizer/renderNestedReferenceProjectsNavbarEl.tsx

https://github.com/ResearchHub/researchhub-web/assets/17622930/93c43d3b-5478-4a3c-8ecd-3ffee4a8c65f

[RefManager] - Active Projects & Refactor & Bugfix

---

components/Comment/CommentEditor.tsx
components/DiscussionCount.js
components/Document/DocumentHeaderV2.tsx
components/Document/DocumentLineItems.tsx
components/Document/api/fetchDocumentMetadata.ts
components/Document/lib/PDFViewer/PDFViewer.tsx
components/Document/lib/types.ts
components/Home/sidebar/sidebar_items/BountiesSidebarItem.tsx
components/Navbar.js
components/ResearchCoin/TransactionCard.js
components/UnifiedDocFeed/UnifiedDocFeedUtil.ts
config/types/contribution.ts
config/types/root_types.ts
pages/stylesheets/App.css

Various small hot-fixes for new doc page

[Doc V3] Exposing reviews, minimal header

---

components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_uploader/ReferenceManualUploadDrawer.tsx
components/contexts/OrganizationContext.tsx
config/api.js
config/killswitch/killswitch_config/killswitch_configs.ts
pages/reference-manager/index.tsx

- depends on https://github.com/ResearchHub/researchhub-backend/pull/1294

[RefManager] - Alpha Release Version

---

components/Document/DocumentHeaderV2.tsx
components/Document/DocumentLineItems.tsx
components/Document/PaperMetadataForm.tsx
components/Document/PaperMetadataModal.tsx
components/Document/api/fetchPaper.ts
components/Document/api/updatePaperMetadataAPI.ts
components/Document/lib/DocumentContext.ts
components/Document/lib/buildOpenGraphData.ts
components/Head.js
components/HorizontalTabBar.tsx
components/Paper/abstract/PaperPageAbstractSection.tsx
components/SearchSuggestion/AuthorInput.js
pages/paper/[documentId]/[documentSlug]/index.tsx
pages/stylesheets/App.css

- Adding ability to edit paper metadata / abstract
- Fixing JSON+LD structured data issues
**Screenshot 1**
**Screenshot 2**
**Screenshot 3**

Edit metadata, JSON+LD

---

components/Document/DocumentHeaderV2.tsx
components/Document/DocumentLineItems.tsx

Fixing merge issues in document page

---

components/Comment/Comment.tsx
components/Comment/CommentFeed.tsx
components/Comment/lib/api.ts
components/Comment/lib/quill/getReviewCategoryScore.ts
components/Comment/lib/types.ts
components/Document/lib/tabbedNavigation.tsx
components/Document/pages/DocumentCommentsPage.tsx
config/types/root_types.ts

Review endpoint not being invoked when peer review comment types are created.
Closes #1465

[Reviews] Fixing Review object not being created

---

components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_table/utils/formatReferenceRowData.tsx

Using pre-signed S3 url to upload files

[Citation Manager] PDF uploads

---

components/Author/Feed/AuthorFeedItem.js

New comments not showing up on profile. Dependent on https://github.com/ResearchHub/researchhub-backend/pull/1300

[Profile] Fixing missing comments in profile page

---

components/ReferenceManager/references/ReferencesContainer.tsx

Calling the pdf callback endpoint manually after a pdf is uploaded with the presigned url
- Only happens in development

QOL for Development with Citation Manager

---

components/DroppableZone.tsx
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/api/postUploadFiles.ts
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
config/api.js

- bugfix double uploading when project is empty
- language update 
- refactor
- type fixes

[RefManager] Bugfix/double upload

---

components/Comment/Comment.tsx
components/Comment/lib/api.ts

[Comments] Bug: Can't load more replies

---

components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/form/ReferenceDoiSearchInput.tsx
components/ReferenceManager/form/api/fetchReferenceFromUrl.ts
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
config/api.js

- https://github.com/ResearchHub/researchhub-backend/pull/1314
!<img width="467" alt="Screenshot 2023-07-07 at 1 53 47 PM" src="https://github.com/ResearchHub/researchhub-web/assets/17622930/7e06dda6-e7db-474f-958f-06b1584daab3">
[Uploading Screenshot 2023-07-07 at 1.53.39 PM.png…]()

[RefManager] - DOI / URL Upload

---

components/Document/lib/PDFViewer/PDFViewer.tsx
pages/paper/[documentId]/[documentSlug]/index.tsx

If PDF Url fails to load, fallback to showing abstract.
Fixes #1511

[Document Page] Fix for bad PDF Url

---

components/Comment/CommentEditor.tsx
components/Comment/hooks/useQuill.tsx
components/Comment/hooks/useQuillContent.ts

[Bug fix] Fix inability to add image when editing comment

---

components/shared/carousel/presets/RhEducationalCarouselElements.tsx

Bringing back "What is ResearchHub?"

What is ResearchHub?

---

components/Notebook/ManageNotePermissions.js
components/Notebook/NoteShareButton.js

Fixes the notebook sharing modal
1. when clicking off the share modal, it should disappear
2. fixes the text overflow

Fixing notebook sharing

---

components/Comment/Comment.tsx
components/Comment/CommentFeed.tsx
components/Comment/CommentReadOnly.tsx
components/Comment/lib/api.ts
components/Comment/lib/config.ts
components/Comment/modules/annotation/AnnotationLayer.tsx
components/Comment/modules/annotation/AnnotationTextBubble.tsx

- Logging comment error in sentry
- Linking conversation to context

Error logging in sentry, "show in context"

---

components/Document/SubmissionDetails.tsx
components/Home/sidebar/RootLeftSidebarSlider.tsx
components/Home/sidebar/sidebar_items/RootLeftSidebarSliderItem.tsx
components/Navbar.js
components/shared/RhTextTag.tsx
pages/stylesheets/App.css

Fixes some mobile issues that make the app look bad

Fix glaring mobile issues

---

components/Author/Tabs/FeedCard.tsx
components/Document/SubmissionDetails.tsx
config/types/bounty.ts
config/types/contentType.ts

Fixed more issues with the submission header on feed cards

More issues fixed

---

components/Comment/modules/annotation/AnnotationLayer.tsx
components/Comment/modules/annotation/lib/xrange/XRange.ts
components/Document/lib/PDFViewer/_PDFViewer.tsx
components/Navbar.js

Fixes #1544 
Fixes #1547 
Fixes #1548 
Fixes #1546

Various hot-fixes related to inline highlighting

---

components/Home/RscBalanceHistoryDropContent.tsx

Balance modal should say "Comment Upvoted"

---

components/Form/FormInput.js
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx

Integrating search into reference manager

Reference Manager Search

---

components/ReferenceManager/references/reference_uploader/reference_upload_utils.ts

Passing in DOI from DOI/url search

[Citation Manager] Manual Entry Bugfix

---

components/Comment/CommentFeed.tsx
components/Comment/lib/config.ts
components/Comment/modules/annotation/AnnotationLayer.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_table/utils/formatReferenceRowData.tsx
components/ReferenceManager/references/styles/ReferencesTableStyles.ts

- Double click to open reference PDF
- Adding comment size limits in ref manager 
- Bug fix: voting hidden in conversation tab

Double click to open ref; bug fixes

---

components/Document/DocumentVote.tsx
components/Modals/ReCaptchaPrompt.js
components/VoteWidgetV2.tsx
pages/Base.js

Override fetch so all 429's will open recaptcha

open recaptcha on all 429

---

components/ReferenceManager/references/reference_item/ReferenceItemDrawer.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_table/utils/formatReferenceRowData.tsx
components/ReferenceManager/references/reference_table/utils/referenceTableFormat.tsx
components/ReferenceManager/references/utils/resolveFieldKeyLabels.ts

- Truncate folder name
- Updating folder name does not show name change until page refresh
- Date misleading
- Escape characters in folder name (should be resolved, but may still have some edge cases)
- Date Misleading fix

Ref improvements

---

components/DroppableZone.tsx
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
components/ReferenceManager/references/reference_organizer/context/ReferenceActiveProjectContext.tsx
components/ReferenceManager/references/reference_organizer/renderNestedReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx

Slugify folders

---

components/Comment/lib/types.ts

Requires: https://github.com/ResearchHub/researchhub-backend/pull/1353

Small Optimization

---

components/ReferenceManager/references/api/fetchCurrentUserReferenceCitations.ts
components/ReferenceManager/references/reference_organizer/context/ReferenceActiveProjectContext.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_table/utils/formatReferenceRowData.tsx
components/ReferenceManager/references/reference_table/utils/referenceTableFormat.tsx
components/ReferenceManager/references/styles/ReferencesTableStyles.ts

- Improved row click interactions (single vs double)
- Smoother UX when switching folders
- Updated colors, icons

[Ref Manager] Click interactions, Loading UX

---

components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/api/postUploadFiles.ts
components/ReferenceManager/references/reference_bibliography/ReferencesBibliographyModal.tsx
components/ReferenceManager/references/reference_item/ReferenceItemDrawer.tsx
components/ReferenceManager/references/reference_table/utils/formatReferenceRowData.tsx
components/ReferenceManager/references/reference_uploader/ReferenceManualUploadDrawer.tsx
components/ReferenceManager/references/reference_uploader/reference_upload_utils.ts
components/ReferenceManager/references/utils/formatCSLDate.ts
components/ReferenceManager/references/utils/resolveFieldKeyLabels.ts

Refactored Zotero inspired variables to CSL standard

CSL Refactor

---

components/Org/NewOrgModal.js
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/api/fetchCurrentUserReferenceCitations.ts
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_table/context/ReferencesTableContext.tsx
components/Tooltips/Organization/OrganizationPopover.tsx

Fix issues of 
1. org switcher and loading state
2. creation of org pushes to reference manager instead of notebook

Reference Manager Bug Fixes

---

components/Banner/constants/exitable_banner_keys.ts
components/Home/sidebar/HomeRightSidebar.tsx
components/Hubs/HubPage.js

Scicon 2023 banner

---

components/Document/DocumentViewer.tsx
components/ReferenceManager/references/api/updateReferenceCitation.ts
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/UploadFileDragAndDrop.tsx
pages/post/[documentId]/[documentSlug]/index.tsx

If PDF url doesn't exist, allow user to upload pdf from doc viewer

Upload pdf from doc viewer

---

components/Document/lib/types.ts
components/Hubs/HubCard.tsx
components/SearchSuggestion/lib/api.ts
config/utils/number.js
config/utils/number.ts
pages/hubs/index.tsx

- Shortened count in hubs page
- Fix broken suggester search in hubs page
- Fix broken global search

Fix hubs endpoint; broken search; shortened count

---

components/Document/DocumentActions.tsx
components/Document/DocumentOptions.tsx
config/types/root_types.ts
pages/paper/[documentId]/[documentSlug]/index.tsx

Remove Post from Feed Button for Admins

Calling endpoint to remove paper from feed

---

components/Comment/CommentFeed.tsx
components/Document/lib/sharedGetStaticProps.ts
components/Document/pages/DocumentCommentsPage.tsx
components/Paper/UploadWizard/PaperUploadWizardStandbyBody.tsx
pages/paper/[documentId]/[documentSlug]/[tabName].tsx
pages/post/[documentId]/[documentSlug]/[tabName].tsx
pages/post/[documentId]/[documentSlug]/index.tsx
pages/question/[documentId]/[documentSlug]/[tabName].tsx
pages/question/[documentId]/[documentSlug]/index.tsx

Hotfix: Preventing statically generated comments to avoid Base64 large image issue

Removing statically generated comments because of base64 issues

---

components/Document/lib/sharedGetStaticProps.ts
components/Modals/UploadPaperModal.js
components/Paper/UploadWizard/PaperUploadWizardUpdatePaper.tsx
config/api.js

Removing unnecessary fields from upload modal. Redirecting to paper page

Removing unnecessary fields from upload modal. Redirecting to paper page

---

components/Author/UserDeleteRequestForm.tsx
components/AuthorClaimModal/AuthorClaimModal.tsx
components/ClaimAuthorPopoverLabel.tsx
components/Form/Button.js
components/Modals/BaseModal.js
components/Modals/UserDeleteRequestModal.tsx
components/shared/ModeratorDashboardSidebar.tsx
package.json
pages/Base.js
pages/moderators/author-claim-case-dashboard/index.tsx
pages/moderators/profile-delete.tsx
pages/moderators/rsc/index.tsx
pages/settings.js
pages/user/[authorId]/[tabName]/index.js
yarn.lock

Delete Account + Author Profile

---

config/utils/isStringURL.ts

No longer using regex to check if a string is a url

Updated URL Check

---

components/Bounty/CreateBountyBtn.tsx
components/Comment/Comment.tsx
components/Comment/CommentActions.tsx
components/Comment/lib/api.ts
components/Comment/lib/bounty.ts
components/Comment/lib/quill/loadQuillModules.tsx
components/Comment/lib/quillPeerReviewRatingBlock.tsx
components/Comment/lib/types.ts
components/ContentBadge.tsx
config/types/bounty.ts

Making the bounty an answer CTA not contribute

Answer bounty

---

config/api.js

Updated query param for filtering excluded documents

Filter Update

---

components/Bounty/BountyModal.tsx
components/Comment/CommentEditor.tsx
components/Comment/CommentFeed.tsx
components/Comment/lib/api.ts
components/Comment/lib/types.ts
components/Comment/lib/types.tsx
components/Form/FormSelect.js
config/types/bounty.ts

Adding bounty types to bounty creation modal

Bounty types

---

components/Author/Tabs/FeedCard.tsx
components/Author/Tabs/ResponsivePostVoteWidget.tsx
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectNavbarElOptions.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_table/context/ReferencesTableContext.tsx
components/UnifiedDocFeed/utils/getDocumentCard.tsx
components/VoteWidget.js

Allow users to drag & drop on left sidebar for ref manager

Reference Manager: Drag & drop on left sidebar

---

components/Comment/modules/annotation/lib/getAnnotationFromPosition.ts
components/Document/DocumentViewer.tsx
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_item/ReferenceItemDrawer.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_table/context/ReferencesTableContext.tsx
components/ReferenceManager/references/reference_table/utils/referenceTableFormat.tsx

Tab structure for reference manager

Reference tabs

---

components/Author/Tabs/FeedCard.tsx
components/Author/Tabs/ResponsivePostVoteWidget.tsx
components/Comment/CommentVote.tsx
components/Document/DocumentHeaderV2.tsx
components/Document/DocumentVote.tsx
components/Document/lib/sharedGetStaticProps.ts
components/Document/lib/types.ts
components/VoteWidget.js

Twitter score feed

---

components/Comment/Comment.tsx
components/Comment/CommentEditor.tsx
components/Comment/CommentFeed.tsx
components/Comment/hooks/useEffectForCommentTypeChange.ts
components/Comment/lib/quill.tsx
components/Home/NavbarRightButtonGroup.tsx
components/Home/sidebar/RootLeftSidebar.tsx
config/types/root_types.ts
next.config.js

- Do not default to 3 star rating for peer reviews
- Turn off referral program for now

Turn off referral program; 3 star rating default;

---

components/Document/DocumentViewer.tsx
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/form/ReferenceDoiSearchInput.tsx
components/ReferenceManager/form/ReferenceItemFieldInput.tsx
components/ReferenceManager/form/ReferenceUploadAttachments.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_item/ReferenceItemDrawer.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/renderNestedReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_table/context/ReferencesTableContext.tsx
components/ReferenceManager/references/reference_table/utils/formatReferenceRowData.tsx
components/ReferenceManager/references/reference_table/utils/referenceTableFormat.tsx
components/ReferenceManager/references/reference_uploader/ReferenceManualUploadDrawer.tsx
components/ReferenceManager/references/reference_uploader/reference_upload_utils.ts
components/ReferenceManager/references/utils/formatCSLDate.ts
components/ReferenceManager/references/utils/resolveFieldKeyLabels.ts
pages/hubs/api/fetchHubFromSlug.ts
pages/reference-manager/index.tsx

Fixes many points in reference metadata

Fix Reference Metadata

---

components/Org/ManageOrgModal.js
components/Org/NewOrgModal.js
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_uploader/ReferenceManualUploadDrawer.tsx
components/ReferenceManager/references/reference_uploader/reference_upload_utils.ts
components/Tooltips/Organization/OrganizationPopover.tsx
components/contexts/OrganizationContext.tsx
pages/reference-manager/index.tsx

Removes "My References" and "Org References" and just initializes "My Library".
Also fixes some bugs with creating a new org in the ref manager

My library

---

components/Org/ManageOrgModal.js
components/Org/NewOrgModal.js
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/form/ReferenceUploadAttachments.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_uploader/ReferenceManualUploadDrawer.tsx
components/ReferenceManager/references/reference_uploader/context/ReferenceUploadDrawerContext.tsx
components/ReferenceManager/references/reference_uploader/reference_upload_utils.ts
components/ReferenceManager/references/utils/resolveFieldKeyLabels.ts
components/Tooltips/Organization/OrganizationPopover.tsx
components/contexts/OrganizationContext.tsx
pages/reference-manager/index.tsx

Creates a PDF from DOI upload if it exists

Fetches PDF from DOI

---

components/Document/DocumentHeaderV2.tsx
components/Document/lib/DocumentPageTutorial.tsx
components/Document/lib/SaveToRefManager.tsx
components/ReferenceManager/basic_page_layout/BasicTogglableNavbarLeft.tsx
components/ReferenceManager/lib/ProjectExplorer.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/api/removeReferenceCitations.ts
components/ReferenceManager/references/reference_organizer/ReferenceProjectNavbarElOptions.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
components/ReferenceManager/references/reference_organizer/context/ReferenceProjectsUpsertContext.tsx
components/ReferenceManager/references/reference_organizer/renderNestedReferenceProjectsNavbarEl.tsx
components/Verification/VerificationForm.tsx
config/hooks/useDismissableFeature.ts

https://www.loom.com/share/70044b5a813b49c996ce94171f63fc21

Save to reference manager

---

components/ReferenceManager/form/ReferenceItemFieldInput.tsx
components/ReferenceManager/menu/DropdownMenu.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_item/ReferenceItemOptsDropdown.tsx
components/ReferenceManager/references/reference_organizer/ReferenceCollaboratorsSection.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/ReferenceProjectsUpsertModal.tsx
components/ReferenceManager/references/reference_organizer/context/ReferenceProjectsUpsertContext.tsx
components/ReferenceManager/references/reference_organizer/renderNestedReferenceProjectsNavbarEl.tsx
components/ReferenceManager/references/reference_organizer/styles/projects_upsert_modal_style.ts
components/ReferenceManager/references/reference_table/ReferencesTable.tsx

Retooling org permissions in folder creation
- Full Access (users can add + remove citations)
- Can View (can only view citations, not add / remove)
- No Access (only you can view the folder)

Setting up org permissions

---

components/Form/FormSelect.js
components/Hubs/HubCard.tsx
components/Hubs/HubSelect.tsx
components/Hubs/HubTag.tsx
components/Question/AskQuestionForm.tsx

- Configure whether badges in "hub select" component should redirect to hub pages or not

Prevent clickability of badges in hub select menu

---

components/Banner/UserStateBanner.js
components/Moderator/ModeratorDeleteButton.js
components/Navbar.js
config/hooks/useCacheControl.ts
pages/user/[authorId]/[tabName]/index.js

Showing suspension / banned banners in offending user's profile. Prior to this we would only show this banner on the currently logged in user's profile

Showing suspension / banned banners in offending user's profile

---

components/Document/pages/DocumentPageLayout.tsx
components/DroppableZone.tsx
components/ReferenceManager/references/ReferencesContainer.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_table/utils/referenceTableFormat.tsx
package.json
yarn.lock

Fixes issue where dropzone doesn't fire sometimes with the table

Fix issue with dropzone

---

components/Document/DocumentViewer.tsx
components/ReferenceManager/references/api/updateReferenceCitation.ts
components/ReferenceManager/references/reference_item/ReferenceItemDrawer.tsx
components/ReferenceManager/references/reference_table/ReferencesTable.tsx
components/ReferenceManager/references/reference_table/context/ReferencesTableContext.tsx
components/ReferenceManager/references/reference_table/utils/referenceTableFormat.tsx

Needed to add X-organization-id to the headers
Also removes scrolling from title and hovering the title in the ref manager will now show the entire title

Fixing PDF not being added to citation

---

components/Document/DocumentViewer.tsx
components/Flag/FlagButtonV2.tsx
components/LiveFeed/Contribution/ContributionEntry.tsx
components/LiveFeed/Contribution/ContributionHeader.tsx
components/LiveFeed/LiveFeed.tsx
components/Paper/Tabs/PaperTab.js
components/shared/GenericMenu.tsx
config/utils/clickEvent.ts
pages/paper/[documentId]/[documentSlug]/index.tsx

- Adding the ability to flag content through the live feed to help with moderation
- Fix "empty box" in paper page when license is "closed access"

Flagging in live feed

---

components/Comment/Comment.tsx
components/Comment/lib/api.ts

Sorting replies to comments by oldest

Reply Sorting

---

components/Document/lib/tabbedNavigation.tsx
components/HorizontalTabBar.tsx

Created a feature indicator that replaces the pill content.

Add new feature indicator to replicability tab

---

components/Org/ManageOrgUsers.js
components/ReferenceManager/form/ReferenceTypeSelect.tsx
components/ReferenceManager/references/reference_item/ReferenceItemDrawer.tsx
components/ReferenceManager/references/reference_uploader/ReferenceManualUploadDrawer.tsx
components/ReferenceManager/references/reference_uploader/reference_upload_utils.ts
components/ReferenceManager/references/utils/resolveFieldKeyLabels.ts

Ref manager fixes

---

components/CKEditor/SimpleEditor.js
components/Form/FormSelect.js
components/Hubs/HubSelectDropdown.tsx
components/Hubs/HubTag.tsx
components/Modals/BaseModal.js
components/Modals/NewPostModal.tsx
components/Paper/Tabs/stylesheets/custom-editor.css
components/Question/AskQuestionForm.tsx
components/ResearchhubOptionCard.tsx

- Various resolution-specific fixes for post modal
- Bug: Hub Select has incorrect position in mobile
- Updated HubSelect to be more mobile friendly
https://www.loom.com/share/cea35ba8291645df81940ab872f26ab2
https://www.loom.com/share/eb3465116c074c058152fbdab6383c05

Improper mobile positioning for Hub Select + various modal fixes

---

components/Banner/constants/exitable_banner_keys.ts
components/Home/sidebar/HomeRightSidebar.tsx
components/Hubs/HubPage.js

Preregistration Funding Banner

---

components/Bounty/BountyModal.tsx
components/Home/RscBalanceButton.tsx
components/Modals/ContentSupportModal.js
components/Modals/PaperTransactionModal.js
components/Modals/constants/SupportContent.ts
components/contexts/ExchangeRateContext.tsx

Re-used fees/total form from Bounty modal to show tipping fees to user.
Also added minimum 10 RSC tip (just on the UI/frontend), b/c some users were spamming 1 RSC tips.

Deduct fees when tipping RSC

---

components/Home/sidebar/HomeSidebarBountiesSection.tsx
components/Home/sidebar/sidebar_items/PeerReviewSidebarItem.tsx
components/Home/sidebar/styles/HomeRightSidebarStyles.ts
components/LiveFeed/api/fetchContributionsAPI.ts
components/Typography/index.js
next.config.js

Adding Peer Review section to bring more awareness to peer reviews

Adding Peer Reviews to Sidebar

---

components/Bounty/BountyInput.tsx
components/Comment/Comment.tsx
components/Comment/lib/options.tsx
components/Question/AskQuestionForm.tsx

Allow users to add a bounty during question creation process
https://www.loom.com/share/84e75e7f92a24c1a9f0a2d2945731cc0

Bounty + Question 

---

components/Home/NavbarRightButtonGroup.tsx
components/Home/RscBalanceButton.tsx
components/Home/sidebar/RootLeftSidebarSlider.tsx
components/Navbar.js
components/Notifications/Notification.js
components/SearchV2/RhSearchBar.tsx
config/themes/colors.js

Inspired by: Notion, Medium, Github

Displaying user nav in mobile

---

components/Author/Tabs/FeedCard.tsx
components/Home/sidebar/RootLeftSidebar.tsx
components/Hubs/HubSelectDropdown.tsx
components/Notifications/Notification.js
components/PermissionsDashboard/Hub/HubEditorCreateForm.tsx
components/PermissionsDashboard/Hub/HubEditorDeleteForm.tsx
components/UnifiedDocFeed/FeedInfoCard.tsx

Fix bug: Editor name missing in Hubs pages
Adding new hub select component to editor dashboard

Hub select in Editor Dash

---

components/Document/lib/SaveToRefManager.tsx
components/Notifications/NotificationEntry.js
components/Notifications/PaperUploadStateNotifier.tsx
components/Notifications/lib/react-toastify-custom.css
components/Notifications/lib/showSaveToRefManagerToast.tsx
components/Notifications/lib/showToast.ts
pages/Base.js
pages/_app.js

- Refactored toast notification so that it can be used from anywhere in the app. Prior to this, it was only scoped to paper upload flow
- Shortened Notification in dropdown. Truncate if beyond 100 characters
-  Added toast to save to reference manager flow.
- Optimistic Save in save to ref manager dialog
https://www.loom.com/share/6cf1fc5569064d72b9226b7a303255e1

Notification related Changes; Toast;

---

components/Modals/WithdrawalModal.js
components/Navbar.js
components/Verification/VerificationFormEmailSentStep.tsx
config/themes/colors.js
next.config.js
pages/user/[authorId]/[tabName]/index.js

- Remove warning banner from user's profile
- Added warning banner to withdrawal modal

Spam warning related changes

---

components/Banner/constants/exitable_banner_keys.ts
components/Home/sidebar/HomeRightSidebar.tsx
components/Hubs/HubPage.js

Funding closed Jan. 15, so we no longer should show the banner.

Remove Preregistration Fundraising Banner

---

components/Comment/CommentAvatars.tsx
components/Fundraise/ContributorsModal.tsx
components/Fundraise/FundraiseCard.tsx

We created an initial test of the new fundraising UI and realized there are some minor bugs/UI issues.

Fix minor bugs on new fundraising UI

---

components/Paper/Tabs/PaperTab.js

Tested locally with data from papers that were flagged by the team and realized there was a logic issue.

Fix bug where all papers were marked as closed access or non-commercial

---

config/api.js

Added temporary shim to fetch recommendations 
e.g. http://localhost:3000/?experiment=recs&user_id=1

Temporary shim to fetch recommendations

---

components/Fundraise/ContributorsModal.tsx
components/Home/sidebar/RootLeftSidebar.tsx
components/Home/sidebar/sidebar_items/RootLeftSidebarItem.tsx
components/Home/sidebar/sidebar_items/RootLeftSidebarSliderItem.tsx
components/Hubs/HubPage.js
components/UnifiedDocFeed/SingleTypeUnifiedDocFeedContainer.tsx

- Added "Funding" to sidebar
- Added "New Feature" indicator
- Fixed bug where UI glitches on first-load
- Improved mobile UI

Push funding live on sidebar and fix minor UI issues

---

pages/about/index.js

Small copy changes to the About page

Copy changes to About page

---

pages/user/[authorId]/[tabName]/index.js

Added "Download as CSV" button to the user profile page

Download RSC Transaction History

---

components/Author/AuthorList.tsx
components/Document/lib/types.ts
components/Navbar.js
components/SearchSuggestion/SearchAutosuggest.tsx
components/SearchSuggestion/lib/api.ts
components/SearchSuggestion/lib/types.ts
components/SearchSuggestion/lib/util.ts
components/SearchV2/RhSearchBar.tsx

- Adding auto-suggest experiment available behind a query string
https://www.loom.com/share/69e1431d5e934b3f8e63977fe123d3af

Auto-suggest experiment

---

components/Author/AuthorList.tsx
components/SearchSuggestion/SearchAutosuggest.tsx
components/SearchSuggestion/lib/util.ts
config/types/root_types.ts

Highlighting author names in search suggestions metadata row

[Search] Highlight author names in search suggestions; related refactor;

---

components/SearchSuggestion/SearchAutosuggest.tsx
components/SearchV2/RhSearchBar.tsx

- Display suggestions drawer in mobile
- Add support for keyboard shortcuts: Enter/Esc/Up/Down

[Search] Display suggestions drawer in mobile; Keyboard support

---

package.json
yarn.lock

- Remove package `react-animated-text`.
- Remove/update other packages as a result of running `yarn remove react-animated-text`.

Housekeeping | Remove unused dependencies

---

components/SearchV2/RhSearchBar.tsx

Remove suggestions feature flag which will turn on the feature to everyone

[Search] Remove feature flag

---

components/Author/Tabs/FeedCard.tsx
components/Comment/lib/colors.ts
components/Search/SearchResultsForDocs.js
config/themes/colors.js

Color scheme matches highlighting in document pages.

[Search] Highlight keywords in title, abstract

---

components/Home/sidebar/RootLeftSidebar.tsx
components/Search/SearchBestResults.js
components/Search/SearchResults.js
components/Search/SearchResultsForDocs.js
components/Search/SearchResultsForHubs.js
components/UserCard.js
config/utils/options.js

- Updating visual design of "Best Results" page to match more closely to design
- Fix broken filters: journal, hubs
- Updated layout to work in mobile
More design work is needed and will follow up next sprint.

[Search] Updating design for best results, fix broken filters

---

components/Comment/CommentFeed.tsx

- Editor type not updating when tabs are changed

[Fix:Comment] Editor type not updating when tabs are changed

---

components/Search/SearchResultsForDocs.js

Fields are now available to include on paper card https://github.com/ResearchHub/researchhub-backend/pull/1521/files

[Search] Adding missing fields to paper card that are now available

---

components/Document/DocumentControls.tsx
components/Document/DocumentViewer.tsx
components/Document/lib/config.ts

- Fix: PDF extends beyond viewport in mobile
- Fix: Align PDF controls against the PDF

[PDF Viewer] Dimension related fixes

---

components/Document/lib/SaveToRefManager.tsx
components/contexts/ReferenceManagerSettings.tsx
pages/Base.js

- Default to last organization, project user saved reference to

[Save to Ref Manager] Auto pick organization last used

---

components/contexts/HistoryManagerContext.tsx
components/contexts/ReferenceManagerSettings.tsx
components/shared/BackBtn.tsx
pages/Base.js

- Do to "shallow" routing in nextjs, back button needs specific handling to work properly

[Fix] Back button not working

---

components/Home/RscBalanceHistoryDropContent.tsx

- To avoid confusion, we shouldn't even open the modal for deposits and withdrawals.
- Deposits are still possible, it just won't register in our system.

Disable withdraw and deposit for now

---

components/Home/RscBalanceHistoryDropContent.tsx

Reverts ResearchHub/researchhub-web#1723

Revert "Disable withdraw and deposit for now"

---

components/Document/api/fetchPostFromS3.ts

Fix youtube video embedding in posts

---

components/withWebSocket.js
config/api.js
config/proxy-api.ts
config/ws.js

This is for testing the new AWS prod environment where we point staging to the new prod backend API.

Point staging to new prod

---

pages/_app.js

maintenance page

---

pages/_app.js

Reverts ResearchHub/researchhub-web#1756

Revert "maintenance page"

---

components/Comment/modules/annotation/AnnotationLayer.tsx

fixes https://github.com/ResearchHub/issues/issues/3

fix: annotations z-index issue fixed

---

components/Document/api/createOrUpdatePostApi.ts
components/Modals/NotePublishModal.tsx
components/Question/AskQuestionForm.tsx

closes [#53](https://github.com/ResearchHub/issues/issues/53).
Dependent on api change https://github.com/ResearchHub/researchhub-backend/pull/1636

Handle API post/question length validation on body, title

---

components/Author/Profile/AuthorHeaderExpertise.tsx
components/Author/Profile/AuthorProfileHeader.tsx
components/Author/lib/ExpertiseModal.tsx
components/Author/lib/ReputationGauge.tsx
components/Author/lib/types.ts
components/Home/sidebar/RootLeftSidebar.tsx
components/Home/sidebar/RootLeftSidebarSlider.tsx
config/themes/colors.js

Closes [#33](https://github.com/orgs/ResearchHub/projects/3/views/3?pane=issue&itemId=65910281)

[Reputation] Rendering gauges

---

next.config.js
pages/api/robots.ts

- Add a `robots.txt` handler for rending a `robots.txt` file based on the environment.
- Disallow crawling in every non-production environment.

Add robots.txt handler

---

.gitignore
package.json

- Remove Docker build scripts from `package.json`.
- Remove Docker files from `.gitignore`.

Cleanup Docker artifacts

---

components/Home/sidebar/RootLeftSidebar.tsx
components/Navbar.js
components/Notifications/Notification.js
components/Notifications/lib/react-toastify-custom.css
components/Notifications/lib/showGenericToast.tsx
components/Notifications/lib/showToast.ts
components/Publication/AddPublicationsModal.tsx
components/Publication/lib/api.ts
components/Publication/lib/sample.json
components/Publication/lib/types.ts
components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
components/Verification/lib/types.ts
components/withWebSocket.js
pages/Base.js

- Add publications modal working end-to-end
- No styling yet

Add Publications modal (no styling, behind feature flag)

---

config/proxy-api.ts

Update the CORS proxy base URLs with the correct URLs of the new environment.

Fix CORS proxy base URLs

---

components/Verification/VerificationWithPersonaStep.tsx

Extract first name and last name from current user and pass them into the Persona component.

Pass first name and last name to Persona

---

components/Author/Profile/AuthorProfileHeader.tsx
components/Modals/UserInfoModal.js
components/Verification/VerificationWithPersonaStep.tsx
components/Verification/VerifyIdentityModal.tsx

- Listen to webhook to know if verification is successful
- Edit profile modal

[Identity verification] Listen to webhook to know if verification is successful (instead of persona default)

---

components/Author/Profile/AuthorActivity.tsx
components/Author/Profile/AuthorComments.tsx
components/Author/Profile/AuthorHeaderAchievements.tsx
components/Author/Profile/AuthorHeaderExpertise.tsx
components/Author/Profile/AuthorHeaderKeyStats.tsx
components/Author/Profile/AuthorProfileHeader.tsx
components/Author/Profile/AuthorPublications.tsx
components/Author/Profile/AuthorSocialMediaIcons.tsx
components/Author/Profile/AuthorWorks.tsx
components/Author/Profile/CoAuthors.tsx
components/Author/Tabs/FeedCard.tsx
components/Author/lib/AuthorReputationSection.tsx
components/Author/lib/ExpertiseModal.tsx
components/Author/lib/ReputationGauge.tsx
components/Author/lib/types.ts
components/Notifications/Notification.js
components/Notifications/NotificationEntry.js
components/UnifiedDocFeed/utils/getDocumentCard.tsx
components/Verification/VerifyIdentityModal.tsx
components/shared/Histogram.tsx
config/hooks/useCacheControl.ts
config/icons/SocialMediaIcons.tsx
config/types/root_types.ts
pages/author/[authorId]/bounties.tsx
pages/author/[authorId]/comments.tsx
pages/author/[authorId]/index.tsx
pages/author/[authorId]/publications.tsx
pages/author/[authorId]/reviews.tsx

- Reducing revalidation TTL on author page to avoid stale content
- Revalidate content after add publications or identity verification
- Do not reset the state of the identity verification modal if closed
- Empty States
- Styles

[Profile] Revalidation, Empty states, styles

---

components/Author/Profile/AuthorComments.tsx
components/Author/Profile/AuthorHeaderAchievements.tsx
components/Author/Profile/AuthorProfileHeader.tsx
pages/author/[authorId]/bounties.tsx
pages/author/[authorId]/comments.tsx
pages/author/[authorId]/index.tsx
pages/author/[authorId]/publications.tsx
pages/author/[authorId]/reviews.tsx

nextjs currently throws an error when retrieving comments on server since some of the comments have serialized images and payload exceeds what it can handle 🤕

Load comments dynamically to avoid nextjs error

---

components/Activity/ActivityDescription.js
components/Author/AuthorList.tsx
components/Author/Feed/AuthorFeedItem.js
components/Author/Feed/ForYouFeedCard.tsx
components/Author/lib/ReputationGauge.tsx
components/AuthorAvatar.js
components/CKEditor/ELNEditor.js
components/Comment/CommentHeader.tsx
components/Comment/CommentHeaderForAnnotation.tsx
components/Comment/lib/quill.tsx
components/Comment/lib/quill/UserBlot.tsx
components/Document/DocumentLineItems.tsx
components/Document/SubmissionDetails.tsx
components/EditorsDashboard/EditorDashboardCard.tsx
components/Fundraise/ContributorsModal.tsx
components/GoogleLoginButton.js
components/Leaderboard/LeaderboardUser.js
components/LiveFeed/Contribution/ContributionAuthor.tsx
components/LiveFeed/Contribution/ContributionHeader.tsx
components/LiveFeed/FlaggedContentDashboard.tsx
components/Modals/PaperTransactionModal.js
components/Navbar.js
components/Notifications/BountyNotifications.js
components/Paper/SideColumn/AuthorCard.js
components/SearchSuggestion/lib/util.ts
components/UserCard.js
config/hooks/useCacheControl.ts
pages/user/[authorId]/[tabName]/index.js

I added a `.next.config.js` level redirect which seems to not work in all cases. This is to explicitly update urls

[Profile] Updating urls from old => new

---

components/Activity/ActivityDescription.js
components/Author/AuthorList.tsx
components/Author/Feed/AuthorFeedItem.js
components/Author/Feed/ForYouFeedCard.tsx
components/Author/lib/ReputationGauge.tsx
components/AuthorAvatar.js
components/CKEditor/ELNEditor.js
components/Comment/CommentHeader.tsx
components/Comment/CommentHeaderForAnnotation.tsx
components/Comment/lib/quill.tsx
components/Comment/lib/quill/UserBlot.tsx
components/Document/DocumentLineItems.tsx
components/Document/SubmissionDetails.tsx
components/EditorsDashboard/EditorDashboardCard.tsx
components/Fundraise/ContributorsModal.tsx
components/Leaderboard/LeaderboardUser.js
components/LiveFeed/Contribution/ContributionAuthor.tsx
components/LiveFeed/Contribution/ContributionHeader.tsx
components/LiveFeed/FlaggedContentDashboard.tsx
components/Modals/PaperTransactionModal.js
components/Navbar.js
components/Notifications/BountyNotifications.js
components/Paper/SideColumn/AuthorCard.js
components/SearchSuggestion/lib/util.ts
components/UserCard.js
config/hooks/useCacheControl.ts
pages/user/[authorId]/[tabName]/index.js

Revert the profile changes in order to analyze impact on infrastructure.
Reverts ResearchHub/researchhub-web#1797

Revert "[Profile] Updating urls from old => new"

---

components/Author/Profile/AuthorHeaderAchievements.tsx
components/Author/Profile/AuthorHeaderKeyStats.tsx
components/Author/Profile/AuthorNavigation.tsx
components/Author/Profile/AuthorProfileHeader.tsx
components/Author/lib/AuthorProfileContext.tsx
components/Author/lib/api.ts
components/Author/lib/types.ts
components/Author/lib/utils.tsx
pages/author/[authorId]/bounties.tsx
pages/author/[authorId]/comments.tsx
pages/author/[authorId]/index.tsx
pages/author/[authorId]/publications.tsx
pages/author/[authorId]/reviews.tsx

Updating profile page to use multiple endpoints instead of one https://github.com/ResearchHub/researchhub-backend/pull/1768

Updating profile page and components to use multiple endpoints

---

components/Author/Profile/AuthorComments.tsx
components/Author/Profile/AuthorProfileHeader.tsx
components/AuthorClaimCaseDashboard/AuthorClaimCaseContainer.tsx
components/AuthorClaimCaseDashboard/api/AuthorClaimCaseGetCases.ts
components/Document/lib/types.ts
pages/author/[authorId]/index.tsx

- Fix issue where mod cases fail to render
- Added loading animation for comments in profile page

Mod cases not showing

---

components/Document/DocumentLineItems.tsx
components/Home/sidebar/HomeRightSidebar.tsx
components/Verification/VerificationSmallBanner.tsx

- Conditionally show verify identity banner
- Turn off author claim in document page (for now)

Conditionally show verify identity banner

---

components/Activity/ActivityDescription.js
components/Author/AuthorList.tsx
components/Author/Feed/AuthorFeedItem.js
components/Author/Feed/ForYouFeedCard.tsx
components/Author/lib/ReputationGauge.tsx
components/AuthorAvatar.js
components/CKEditor/ELNEditor.js
components/Comment/CommentHeader.tsx
components/Comment/CommentHeaderForAnnotation.tsx
components/Comment/lib/quill.tsx
components/Comment/lib/quill/UserBlot.tsx
components/Document/DocumentLineItems.tsx
components/Document/SubmissionDetails.tsx
components/EditorsDashboard/EditorDashboardCard.tsx
components/Fundraise/ContributorsModal.tsx
components/Leaderboard/LeaderboardUser.js
components/LiveFeed/Contribution/ContributionAuthor.tsx
components/LiveFeed/Contribution/ContributionHeader.tsx
components/LiveFeed/FlaggedContentDashboard.tsx
components/Modals/PaperTransactionModal.js
components/Navbar.js
components/Notifications/BountyNotifications.js
components/Paper/SideColumn/AuthorCard.js
components/SearchSuggestion/lib/util.ts
components/UserCard.js
config/hooks/useCacheControl.ts
pages/user/[authorId]/[tabName]/index.js

Reverts ResearchHub/researchhub-web#1798

Revert "Revert "[Profile] Updating urls from old => new""

---

components/AuthorClaimCaseDashboard/AuthorClaimCaseCardTargetAuthorSection.tsx
components/AuthorClaimCaseDashboard/AuthorClaimCaseModal.tsx
components/AuthorClaimCaseDashboard/api/AuthorClaimCaseGetCases.ts

Displaying claiming user email in mod dash

[Author Claim] Adding claiming user email

---

components/Author/lib/api.ts
pages/author/[authorId]/bounties.tsx
pages/author/[authorId]/comments.tsx
pages/author/[authorId]/index.tsx
pages/author/[authorId]/publications.tsx
pages/author/[authorId]/reviews.tsx

- Avoid fetching overview in non-overview tabs
- Fix broken references to `overview` in non-overview tabs

Fix incorrect broken references/loading in author pages

---

components/Bounty/BountyModal.tsx
components/Comment/CommentEditor.tsx
components/Comment/CommentFeed.tsx
components/Comment/lib/api.ts
components/Hubs/api/fetchReputationHubs.ts
components/Notifications/NotificationEntry.js
config/types/bounty.ts
config/types/hub.ts

- For you bounty notifications
- Optional audience targeting when creating bounties based on expertise

"For You" Bounty notifications; Optional targeting based on expertise;

---

components/Author/AuthorList.tsx
components/Bounty/api/fetchBountiesAPI.ts
components/Home/sidebar/RootLeftSidebar.tsx
config/types/contribution.ts
config/types/root_types.ts
pages/bounties/index.tsx

Bounties page

---

components/Author/Tabs/FeedCard.tsx
components/ResearchCoin/lib/rewardsUtil.ts
components/shared/ClaimRewardsButton.tsx
config/utils/dates.js

- Update FeedCard to display published date instead of created date
- Added Open Access requirement for claim initiation
- Added five year requirement for claim initiation

[Paper Claim] Updating claim requirements

---

components/Bounty/api/fetchBountiesAPI.ts
components/Home/sidebar/RootLeftSidebar.tsx
components/Home/sidebar/RootLeftSidebarSlider.tsx
components/HorizontalTabBar.tsx
components/UnifiedDocFeed/FeedInfoCard.tsx
pages/bounties/index.tsx

- Enabling bounties page by exposing in left sidebar
- Pagination for bounties page

Enable bounties page

---

components/Author/Profile/AuthorProfileHeader.tsx
components/Modals/WithdrawalModal.js
components/Moderator/lib/api.ts
components/Moderator/lib/types.ts
config/hooks/useCurrentUser.ts
config/utils/dates.js
pages/author/[authorId]/index.tsx

Moderation section; Update withdrawal message;

---

components/Hubs/HubSelect.tsx

Closes https://github.com/ResearchHub/issues/issues/132

[Journals] Updating default sort order to be page count

---

components/Comment/CommentEmptyState.tsx
components/LiveFeed/LiveFeed.tsx
pages/grants/index.tsx

Closes https://github.com/ResearchHub/issues/issues/133

[Grants] Rename bounty => grant

---

components/Home/sidebar/RootLeftSidebar.tsx
components/Modals/WithdrawalModal.js
components/PeerReviews/RhPeerReviewCarouselElement.tsx
pages/researchhub-journal/index.tsx

- Make sidebar sticky since it has gotten longer.
- Change '21 days from submission to peer review completion" to "14 days..."
- Move "NEW" tag in verification carousel element to the right side.

sticky side, rh-journal copy, and verification carousel "NEW"

---

components/Home/sidebar/RootLeftSidebar.tsx
components/Home/sidebar/RootLeftSidebarSlider.tsx

Move Social links up & Add "Support" on mobile view

---

components/PermissionsDashboard/Hub/HubEditorCreateForm.tsx
components/PermissionsDashboard/api/hubEditorCreate.ts

researchhub/issues#115
Added dropdown to select editor type

Tiered Editors

---

components/PermissionsDashboard/Hub/HubEditorCreateForm.tsx

Cleans up the editors dashboard UI

Editor Dashboard UI Cleanup

---

components/Home/sidebar/HomeRightSidebar.tsx
components/Home/sidebar/RootLeftSidebar.tsx
components/Home/sidebar/UnifiedCarousel.tsx
components/ResearchHubJournal/RhJournalCarouselElement.tsx

journal-carousel item & fixed icons on left sidebar

---

components/Ethereum/ETHAddressInput.js
components/Modals/WithdrawalModal.js

- Fix capitalization
- Don't show valid address on empty address
- Update descriptions on networks dropdown

Round transaction fee on backend

---

components/Document/lib/tabbedNavigation.tsx

fix: show peer reviews and grants on preregistrations

---

components/Document/lib/PaperVersion/PaperVersionPublishInJournalIntroStep.tsx

Update UI to reflect Kobe's backend change to $0 APC charge temporarily

update-apc/ 0 USD APC

---

components/Document/DocumentOptions.tsx
components/Document/pages/DocumentChangesPage.tsx
components/NewPostButton.tsx

- Fix incorrect argument name
- Fix incorrect argument values

Fix previous paper version issue

---

pages/Base.js

With the migration of the new website to www.researchhub.com, update the banner with the following text:
> You are viewing an outdated version of ResearchHub. Visit the latest version →

Update former banner informing about "new" website
