ResearchHub/researchhub-web

components/Author/Tabs/UserTransactions.js, components/ResearchCoin/TransactionCard.js, config/api.js, pages/user/[authorId]/[tabName]/index.js, redux/configureStore.js, redux/transaction.js
Changing the frontend to get back all transaction data, not just withdrawals. 
This allows users to see what earned them RSC and also what they spent their RSC on. 
Currently doesn't have any links to papers / comments but working on getting that in too.
=> All transaction data

components/AuthorClaimCaseDashboard/AuthorClaimCaseCard.tsx, components/AuthorClaimCaseDashboard/AuthorClaimCaseCardTargetAuthorSection.tsx, components/AuthorClaimCaseDashboard/AuthorClaimCaseModal.tsx, components/AuthorClaimCaseDashboard/api/AuthorClaimCaseGetCases.ts, components/AuthorClaimCaseDashboard/api/AuthorClaimCaseUpdateCase.ts, components/AuthorClaimCaseDashboard/constants/AuthorClaimStatus.ts, components/AuthorClaimCaseDashboard/util/AuthorClaimCaseUtil.ts, components/AuthorClaimModal/AuthorClaimPromptEmail.tsx, components/AuthorClaimModal/api/authorClaimCaseCreate.ts, pages/user/[authorId]/[tabName]/index.js
- Rendering associated paper in editor dash. The paper indicates where the claim was opened.
- Removing claim functionality from author page.
=> [Claim Dash] Adding Claim Context

components/UnifiedDocFeed/api/unifiedDocFetch.js
- At the moment, our time filters are off. For example, if today's date is 03-01 then "This month" will only show things that happened today. 
- I confirmed that reddit works differently. Selecting any time filter will subtract an absolute number of days from today. For example, When applying "This month" in reddit, reddit will show posts in the past 30 days.
- Doing things this way gets around the problem of different client timezones. In NYC "today" means a different epoch than in the west coast.
=> Updating start_date on feed to be based on absolute time rather than relative

components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx, components/UnifiedDocFeed/api/unifiedDocFetch.js, components/UnifiedDocFeed/utils/UnifiedDocFeedUtil.tsx, components/UnifiedDocFeed/utils/getDocumentCard.tsx
- Component re-render was resetting locally memoized variable for the prefetch function
- Made the function into a state of the top-level component
- Added force reset on the refetch on doc-type changes
=> [Feed][Bugfix] - Prefetch local var resetting on component rerender

components/DiscussionPostMetadata.js, config/utils/dates.js
- Fix for comment timestamps incorrectly rounding. For example, "13 days ago" would be rounded to "1 week ago".
- This leads to incorrect output and also makes it hard to debug the "discussed" filter.
- Confirmed that we do not have a function that does this in the codebase. Also confirmed that daysjs does not have a utility function as such.
=> Comment timestamps rounded incorrectly using TimeAgo

README.md
The link was previously updated in c73de9f1d274e890c56b28568459174b60ceda4f but the label and icon were not.
| Before | After |
| --- | --- |
| <img width="194" alt="image" src="https://user-images.githubusercontent.com/29494270/182364129-74015476-a7ee-4737-9296-b23d4697f37a.png"> | <img width="208" alt="image" src="https://user-images.githubusercontent.com/29494270/182364053-ba5e488f-e221-48d2-ba21-0e4492048e16.png"> |
=> Change community badge icon from Slack to Discord

pages/paper/[paperId]/[paperName]/index.js
**Explanation**
Has to do with static site generation. Nextjs will not unmount the current component which means we need to reset the paper in the page itself.
=> Fix: Clicking paper page URL in notification does not change pages

components/shared/carousel/presets/RhEducationalCarouselElements.tsx
This tries out the idea of calling ResearchHub a modern day pre-print server, while still highlighting the broader capabilities of the open science platform.
We can play with variations of this over time - I just wanted to try some variations of the copy for first time visitors to the site.
=> Update welcome banner text

components/ReferenceManager/references/ReferencesContainer.tsx, components/ReferenceManager/references/reference_item/ReferenceItemDrawer.tsx, components/ReferenceManager/references/reference_item/ReferenceItemOptsDropdown.tsx, components/ReferenceManager/references/reference_table/ReferencesTable.tsx, components/ReferenceManager/references/reference_table/utils/formatReferenceRowData.tsx, components/ReferenceManager/references/reference_table/utils/referenceTableFormat.tsx, components/ReferenceManager/references/styles/ReferencesTableStyles.ts, config/utils/clickEvent.ts, config/utils/device.ts
At a high level, configured row selection mechanism to work like Dropbox and Google Drive for desktop and touch-enabled devices.
=> Row selection-related reference manager fixes

components/Hubs/api/fetchHubs.js, components/shared/Pagination.tsx, config/api.js, pages/hubs/index.tsx, redux/hub.js
Implement pagination on hubs.
- Created a custom `Pagination` component with custom styling
- Changed `ordering` query param from `score` to `-score` (This is in conjunction with a backend change)
- `-score` means descending order, which is what we want, we perviously just did some weird stuff on the backend to make this work with `score`.
=> Add Pagination to Hubs

pages/hubs/index.tsx
Minor bug where query param wasn't getting reset to page 1 when sorting was changed on hubs.
=> Bug Fix: Reset query param when changing sorting on hubs

components/Author/Feed/utils/AuthorFeedUtils.js, pages/_app.js, pages/user/[authorId]/[tabName]/index.js
**Fix 1:** There is a bug on the profile page where the loader persists on-screen and doesn't go away.
After debugging I found that the `router.events.on("routeChangeError")` would get called with `"Error: Cancel rendering route ..."`, and `routeChangeComplete` would not get called as a result. So the `showLoader.current` timer wouldn't get cleared and would dispatch a `MessageActions.showMessage({ show: true, load: true })` action.
The reason why we get that error is because we make route changes in two places:
1. `router.push` in [handleTabClick](https://github.com/ResearchHub/researchhub-web/blob/master/pages/user/%5BauthorId%5D/%5BtabName%5D/index.js#L228-L252)
2. using the [href tag](https://github.com/ResearchHub/researchhub-web/blob/master/pages/user/%5BauthorId%5D/%5BtabName%5D/ind …
=> Fix bug where loader persisted on profile page

components/ReferenceManager/form/ReferenceItemFieldAttachment.tsx, components/ReferenceManager/references/reference_item/ReferenceItemDrawer.tsx
Decided to just add a "Remove" button within the existing "Edit Metadata" menu since this is where users would go to edit the rest of the citation's contents.
It also simplified the UX/implementation.
=> Add ability to remove PDF from citation

components/ReferenceManager/references/ReferencesContainer.tsx, components/ReferenceManager/references/reference_import_library_modal/ReferenceImportLibraryModal.tsx, components/ReferenceManager/references/reference_table/ReferencesTable.tsx
This was discussed in last Friday's meeting with Brian.
We wanted to allow users to drag and drop BibTeX files into the main view, to increase discoverability and usability.
=> Allow users to drag and drop .bib files in reference manager

components/Author/Tabs/FeedCard.tsx, components/ContentBadge.tsx, components/Document/lib/DocumentHubs.tsx
Badges were stacking too far. Instead of overflowing them down to the next row (looks strange), moved the hub badge above all other badges on mobile.
=> Home page on mobile broken

components/Paper/abstract/PaperPageAbstractSection.tsx
There was a runtime bug where `paper.hubs` was undefined, so trying to call `.map` threw an error.
After looking into it, it doesn't seem like we need to pass `hubs` in the request body (correct me if I'm wrong).
I tried updating abstracts on papers with and without hubs and the request works successfully, and hubs remain unchanged.
=> Fix bug where abstract couldn't be updated in paper page

components/ReferenceManager/menu/QuickModal.tsx, components/ReferenceManager/references/ReferencesContainer.tsx, components/ReferenceManager/references/reference_bibliography/ReferencesBibliographyModal.tsx, components/ReferenceManager/references/reference_bibliography/export.ts, config/utils/nullchecks.ts, package.json, yarn.lock
Add support for exporting references as BibTeX and RIS.
I also made a small change to `<QuickModal>` since the button colouring/styling didn't match the rest of our UI and it was bothering me.
Updated UI for APA to include scrolling section for long reference lists.
Exporting BibTeX or RIS directly opens save window.
=> Export references as BibTeX and RIS

components/Home/sidebar/RootLeftSidebar.tsx, components/Home/sidebar/RootLeftSidebarSlider.tsx, components/Paper/Tabs/DiscussionTab.js, components/ShareDropdown.tsx, components/VoteWidget.js, config/themes/iconsToModify.js, pages/footer.js, pages/hubs/index.tsx, pages/user/[authorId]/[tabName]/index.js
Hide pagination when searching hubs.
Update remaining Twitter logos to X. (this was bothering me)
- Kept copy as "X / Twitter"  to limit confusion
=> Hide pagination when searching hubs & update remaining Twitter logos

components/Document/pages/DocumentReplicationMarketPage.tsx, components/PredictionMarket/PredictionMarketVoteForm.tsx
Move votes tab first and move tooltip text to subtitle.
<br /> <br />
Also added more robust logic to associate votes with current user. Since it wasn't working when doing votes in prod.
=> Multiple UI improvements and fixes to Replication Voting

components/Author/Tabs/FeedCard.tsx, components/UnifiedDocFeed/utils/getDocumentCard.tsx
Removing used `boost_amount`
Using hubs from unified document instead of document
Bounty logic now uses bounty information from `document_filter`
=> Small FeedCard Update

pages/product/reference-manager/index.tsx
Brian mentioned that it'd be useful to have a more descriptive title on the landing page.
The team decided that "A Reference Manager Built for Labs" would be a better option.
=> Update ref manager landing page header copy

components/Document/DocumentViewer.tsx, components/Document/lib/PDFViewer/_PDFViewer.tsx, components/Document/lib/config.ts
Enabled annotations on PDFs and got hyperlinks and anchor links working.
- Hyperlinks open the link in a new tab
- Anchor links scroll to the page where the reference is
Tested viewers on both paper page and reference manager:
- Desktop (Brave, Chrome, Safari, Firefox)
- Mobile (Brave)
Checked bundle/build sizes and didn't see any increase.
=> Get hyperlinks and anchors working with PDFs

components/ResearchCoin/TransactionCard.js
In #1659, I referenced an object `withdrawal`, when I should have referenced `transaction` ([direct link to code](https://github.com/ResearchHub/researchhub-web/pull/1659/files#diff-10ab370752364b096b3b7edde66413ffdb689293efde6245c376222b656b9b7aR97-R98)). This was a mistake made when copy-pasting from another file.
=> Fix bug that breaks profile page caused by nonexistent variable

components/Comment/lib/quill.css
- Reported on discord
- Cannot enter whitespace in comment editor
- Reported in quill rep: https://github.com/quilljs/quill/issues/1874
=> Cannot enter whitespace in Firefox

components/Document/PaperMetadataForm.tsx, components/Document/api/updatePaperMetadataAPI.ts, components/Document/lib/types.ts, components/LiveFeed/Contribution/ContributionEntry.tsx, components/LiveFeed/FlaggedContentDashboard.tsx, components/LiveFeed/api/removeFlaggedPaperPDFAPI.ts, components/Paper/Tabs/PaperTab.js, config/types/licenseOptions.ts
- Update copy when PDF isn't viewable
- Use new `pdf_copyright_allows_display` flag from backend to determine whether to enable PDF Upload
- User-uploaded PDF shows in reference manager, even if paper has copyright restrictions
- Saving a paper to the reference manager with a copyrighted PDF won't copy the PDF to the citation
- Let moderators remove PDF from moderator panel
- Let moderators edit license metadata
https://www.loom.com/share/e5681b0ccff342f783c5a91c1bbf8835?sid=c0dcf2e2-29f5-4c61-8d26-36fc00e0b9b3
- Should Show PDF: `oa_status = null` and `pdf_license = cc-by`: https://researchhub-web-git-manveer-pdf-licenses-researchhub.vercel.app/paper/131491/the-lbca-lipoprotein-and-ctpa-protease-assemble-an-oligomeric-complex-to-control-peptidoglycan-hydrolases-in-ipseudomonas-aeruginosai …
=> Improve how we handle copyrighted PDFs

components/Document/DocumentLineItems.tsx, components/Paper/Tabs/PaperTab.js
There were a bunch of papers failing to render on the server side because of a `null` value in a `href` tag.
It seems like this may have been caused by `paper.url = null`, and may have newly been surfaced as an issue when we made the change to copyright handling (https://github.com/ResearchHub/researchhub-web/pull/1658).
=> Fix bug where null href caused paper page to crash

components/Bounty/BountyModal.tsx, components/Bounty/BountyWizardRSCForm.tsx, components/Bounty/config/constants.ts, components/Modals/ContentSupportModal.js, components/Modals/PaperTransactionModal.js
- Reduce bounty minimum to 10
- Modify logic to allow 10 as a minimum, rather than requiring more than 10 (e.g. 11)
- Update copy for support fee as we're moving the full 3% to RH Inc.
=> Update UI for bounty minimum and support tipping fee changes

components/Fundraise/FundraiseCard.tsx, components/Fundraise/lib/types.ts
This PR builds on the backend change (https://github.com/ResearchHub/researchhub-backend/pull/1434) to add a new "COMPLETED" status to a fundraise.
It's meant to fix the bug where RSC price fluctuations caused completed fundraises to show as closed.
Closed fundraise looks like this:
=> Fix bug where completed fundraise would show as closed

components/Document/api/fetchPostFromS3.ts, package.json, yarn.lock
Sanitize post html before rendering to avoid XSS attacks. I decided to just use the default attributes listed here https://github.com/apostrophecms/sanitize-html?tab=readme-ov-file#default-options plus video and tested it by creating a note with each of the rich editing features. 
We are not sanitizing the notebooks on creation because we will be migrating away from CKEditor so we will address those changes along with a sanitization of any existing notes.
=> Sanitize post html before rendering

components/Author/AuthorList.tsx, components/SearchSuggestion/SearchAutosuggest.tsx, components/SearchSuggestion/lib/api.ts, components/SearchV2/RhSearchBar.tsx
- Only show one author in search results for width purposes
- Format number of papers in hub results to include a comma
- Debounce calls to suggest endpoint
- Ensure that if one result fails to parse, the whole result set doesn't
=> Various hotfixes for search suggestions

.github/CODEOWNERS
Make the new @ResearchHub/engineers team the code owner of this repository. The team will be automatically requested for review when a pull request is opened.
=> GitHub | Add code owners

README.md
Add a note about `gyp` errors associated with the `canvas` native dependency when building with `yarn install`.
=> Docs | Add macOS notes

components/Document/pages/DocumentPageLayout.tsx, components/Head.js, components/SearchSuggestion/SearchAutosuggest.tsx, components/SearchV2/RhSearchBar.tsx
- Prevent zoom in on search input in mobile when focused
- Changing height of suggestion results
- Back arrow in mobile does not work
=> [Search] Mobile fixes

components/Home/NavbarRightButtonGroup.tsx, components/SearchV2/RhSearchBar.tsx, config/api.js
- Do not debounce when user presses "Enter" key
- Do not auto-open suggestion drawer on page load
- Close suggestion drawer when notification btn is clicked on
- Remove `external_source` property which applies filter incorrectly and causes results not to show in search results page
=> [Search] Various UX fixes

components/Login/LoginModal.tsx
When logging in with username and password, set the focus on the password field, so the user does not need to manually focus the password field.
=> Set focus on password field after entering email

components/CKEditor/ELNEditor.js, components/Document/lib/DocumentPostPageType.tsx, components/ReferenceManager/references/ReferencesContainer.tsx, pages/stylesheets/App.css, pages/viewer/index.tsx
Quick fix for: https://github.com/ResearchHub/issues/issues/4
This isn't 100% the right way to fix the issue. The reason the issue is happening is because we're rendering raw HTML, which doesn't work 100% with CKEditor.
We should be rendering a readonly instance of CKEditor inside the `<DocumentViewer />`. This will take longer to get right because there are quirky things about CKEditor. The reason we should be rendering CKEditor inside the DocumentViewer is because CKEditor does some kind of postprocessing on the HTML.
=> Post quick fix

components/AuthorClaimCaseDashboard/AuthorClaimCaseContainer.tsx, components/AuthorClaimCaseDashboard/api/AuthorClaimCaseGetCases.ts
- Wrap each claim processing with try/catch to avoid crashing the mod dash
=> Avoiding crashing the whole moderator dash if error is thrown on claim

next.config.js
- Remove the key for `sentry`.
- Move the option for hidden source maps to the Sentry section.
This will fix the following warning messages when running a build:
```
- warn Invalid next.config.js options detected: 
- warn     The root value has an unexpected property, sentry, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, configOrigin, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, …
```
=> Fix unknown setting warning

.github/workflows/mirror-master.yml
This change adds a Github Action that mirrors the `master` branch on every push in `master-mirror`. The mirrored branch will be used as the base branch for a staging environment in Vercel.
Closes researchhub/issues#75
=> Add Github Action to mirror master branch

components/Publication/lib/api.ts
Use the `/author/<ID>/publication` resource for creating author-publication relations (i.e., `POST`ing to the resource).
=> Use publication resource for add publications

components/Navbar.js
Set a title for the author profile page instead of the default _Explore ResearchHub_.
=> Set "Author" as the title for the author profile page

components/Author/Profile/AuthorHeaderExpertise.tsx, components/Author/Profile/AuthorProfileHeader.tsx, components/Author/Profile/AuthorPublications.tsx, components/Author/Profile/WelcomeToProfileBanner.tsx, components/Author/lib/types.ts, components/ResearchCoin/lib/rewardsUtil.ts, components/Verification/VerifyIdentityModal.tsx, components/shared/ClaimRewardsButton.tsx, config/types/root_types.ts
- Dismissible banner in profile page
- Refactor of Claim Rewards button 
- Added disabled state for claim rewards
=> [Profile] Rewards related changes

components/Tooltips/RSC/RSCTooltip.tsx, components/Tooltips/User/UserTooltip.tsx
Check if user ID is present before rending the `UserPopover` component. In the current form, a `UserPopover` gets rendered with a user ID of `undefined`. This in turn invokes requests to the backend that causes unhandled error (which will be addressed in a separate PR).
=> Check for user ID in `UserPopover` component

components/Author/Profile/AuthorPublications.tsx, components/Author/Tabs/FeedCard.tsx, components/Document/lib/types.ts, components/Notifications/NotificationEntry.js, components/ResearchCoin/ClaimRewardsModal.tsx, components/ResearchCoin/lib/api.ts, components/ResearchCoin/lib/rewardsUtil.ts, config/types/root_types.ts
- Refactored references to `authorship` to rely on new data structure explained https://github.com/ResearchHub/researchhub-backend/pull/1822
- Removed requirement of sending authorship ID when opening a claim
=> Remove authorship in paper claim process

pages/_app.js
The default transaction sample rate for the Elastic APM client is 100% which is not needed. This change reduces the sample rate to 10% (aligning with the backend configuration applied a few months back).
See: https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#transaction-sample-rate
=> Reduce APM transaction sample rate to 10%

components/UnifiedDocFeed/FeedInfoCard.tsx, components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
The paper/discussion count on hub pages is not easily readable:
This change aligns the display count to the same format as used on the hub listing page:
=> Shorten displayed document count

components/Document/SubmissionDetails.tsx, components/EditorsDashboard/EditorDashboardCard.tsx, components/HubLeaderDashboard/HubLeaderDashboardCard.tsx, components/Hubs/HubTag.tsx, components/Modals/EditHubModal.js, components/SearchSuggestion/SearchAutosuggest.tsx, pages/hubs/[slug]/index.js, pages/hubs/[slug]/live.tsx
Stop title-casing hub names. Previously, hub names were returned all lowercase by the backend. With https://github.com/ResearchHub/researchhub-backend/pull/1891, the backend will return hub names as-is (mixed-case) which should be preserved as returned.
Closes https://github.com/ResearchHub/issues/issues/117
=> Stop title-casing hub names

components/Author/lib/ExpertiseModal.tsx
Currently the link "Learn more about our reputation algorithm" point to the homepage. This change updates the link to point to the reputation v2 post (https://www.researchhub.com/post/3019/reputation-v2-healthy-research-rewards).
=> fix: Add link to reputation v2 post

pages/user/[authorId]/[tabName]/index.js
Changes for ResearchHub/researchhub-backend/pull/1851:
Download the returned CSV directly instead of extracting it from a JSON object.
=> Fetch CSV from endpoint instead of extracting from JSON

config/utils/dates.js
Take years and months already displayed into account.
So instead of:
> Member since 2 years, 27 months and 851 days
Show this:
> Member since 2 years, 4 months and 1 day
Fixes https://github.com/ResearchHub/issues/issues/122
=> fix: Correctly display "member for" period in years, months, days

components/Hubs/HubCard.tsx, components/Hubs/HubSelect.tsx, components/Modals/EditHubModal.js
Copy and pasting longer strings into the hub description field when editing hubs has no effect. This change increases the character limit for the description field from 150 to 500 characters. This is fully supported by the backend (type `TEXT`) and the hub card will continue to display the description truncated to 150 characters.
Fixes https://github.com/ResearchHub/issues/issues/130
=> fix: Copy and paste to hub description does not work

components/Home/sidebar/RootLeftSidebar.tsx
Before:
16" Mac screen showed sidebar scrollbar always
=> Prevent sidebar scrollbar rendering on Mac 16" and other

components/Home/RscBalanceButton.tsx, config/utils/form.js
- Since we only provide 0.01 RSC per upvote, we should show more decimals in our balance since.
=> Round balance since last seen to two decimals

components/Document/lib/PaperVersion/PaperVersionModal.tsx
At least one author provided in the paper version modal must be the corresponding author. If none is provided, show an error message and don't let the user advance to the next screen.
=> Add check for corresponding author

components/Document/api/createPaperAPI.ts
When paper versions are created, we currently swallow the errors although there is explicit error handling in the client code.
=> Don't swallow errors when creating paper versions

components/Notebook/NewNoteBanner.js, components/Notebook/Notebook.js
- This PR adds support for detecting and handling "new" notes(`note.json`) created in our new notebook. When a user opens a new note, they'll see a banner with a link to edit it in the New Web app.
- Created a separate Banner component and render it for "New" notes
=> New Note Banner

components/CKEditor/ELNEditor.js, components/CKEditor/SimpleEditor.js, components/Modals/NoteTemplateModal.tsx, components/withWebSocket.js, config/api.js, config/api/api.js, config/auth/ensureAuthenticated.ts, config/utils/auth.js, pages/[orgSlug]/notebook/[noteId]/index.tsx, pages/[orgSlug]/notebook/index.js, pages/for-you/index.js, pages/funding/index.tsx, pages/live/index.tsx, pages/most-discussed/[scope]/index.js, pages/most-discussed/index.js, pages/newest/[scope]/index.js, pages/newest/index.js, pages/notebook/index.tsx, pages/pulled-papers/index.js, pages/recs/index.tsx, pages/reference-manager/index.tsx, pages/referral/index.js, pages/removed/[scope]/index.js, pages/removed/index.js, pages/search/[type]/index.js, pages/top-rated/[scope]/index.js, pages/top-rated/index.js, redux/auth.js
- Implemented cookie sharing mechanism in the old app to enable cross-application authentication with the new NextJS app
- Maintains backward compatibility while adding support for environment-specific auth tokens
- Introduces shared auth token utilities in `config/utils/auth.js`:
- Environment-prefixed token names (e.g., `prod.researchhub.auth.token`)
- Token priority handling (checks old token first, then env-specific)
- Updates auth token handling:
- Sets both old and new tokens on login/register
- Removes both tokens on logout
- Maintains backward compatibility by keeping original token behavior
- Cookie Configuration:
- Production: `.researchhub.com`
- Staging: `.staging.researchhub.com`
- Local: `localhost`
=> Share session between old and new apps

components/Login/LoginModal.tsx
On mobile, disable auto-capitalization of email address in login field.
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/autocapitalize
=> Disable auto capitalization of email address

components/ResearchHubBanner.js, components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx
=> Fix typo in ResearchHub banner
